class CPlusPlusQuestionsEn {
  static const List<String> junior = [
    "What is C++ and how does it differ from C?",
    "How is a C++ program compiled?",
    "What are the main data types in C++?",
    "How do you declare a variable in C++?",
    "What is variable scope?",
    "What type modifiers exist?",
    "How do branching operators work (if/else, switch)?",
    "What loops exist in C++ (for, while, do-while)?",
    "How to use the break operator?",
    "How does the continue operator work?",
    "What is the ternary operator?",
    "How do logical operators work?",
    "How to use bitwise operators?",
    "What is the sizeof operator?",
    "How do the new and delete operators work?",
    "What are pointers and how to use them?",
    "How to work with arrays?",
    "What are strings in C++?",
    "How to use std::string?",
    "What are structures (struct)?",
    "How to declare and use enumerations (enum)?",
    "What are unions?",
    "How to work with functions?",
    "What are function prototypes?",
    "How to pass parameters to functions?",
    "What is a function's return value?",
    "How to use default parameters?",
    "What is function overloading?",
    "How to work with header files?",
    "What are preprocessor directives?",

    "What are classes and objects?",
    "How to create a class in C++?",
    "What are constructors and destructors?",
    "How to use initializer lists?",
    "What is the this pointer?",
    "How does inheritance work?",
    "What is polymorphism?",
    "How to use virtual functions?",
    "What are abstract classes?",
    "How do pure virtual functions work?",
    "What is encapsulation?",
    "How to use access specifiers?",
    "What are friend functions?",
    "How to use static class members?",
    "What are const member functions?",
    "How to overload operators?",
    "What is a copy constructor?",
    "How does the assignment operator work?",
    "What is the Rule of Three?",
    "How to use move semantics?",
    "What is RAII?",
    "How to work with class templates?",
    "What is template specialization?",
    "How to use namespaces?",
    "What are anonymous namespaces?",

    "How does dynamic memory allocation work?",
    "What are the stack and the heap?",
    "How to use malloc and free?",
    "How do new/delete differ from malloc/free?",
    "What are memory leaks?",
    "How to avoid memory leaks?",
    "What are smart pointers?",
    "How to use unique_ptr?",
    "What is shared_ptr?",
    "How does weak_ptr work?",
    "What are cyclic references?",
    "How to use make_shared and make_unique?",
    "What is placement new?",
    "How to work with allocators?",
    "What is a custom deleter?",

    "How to work with std::vector?",
    "What is std::array?",
    "How to use std::list?",
    "What is std::forward_list?",
    "How to work with std::deque?",
    "What are std::set and std::multiset?",
    "How to use std::map and std::multimap?",
    "What is std::unordered_map?",
    "How to work with std::pair?",
    "What is std::tuple?",
    "How to use std::string_view?",
    "What is std::optional?",
    "How to work with std::variant?",
    "What is std::any?",
    "How to use STL algorithms?",
    "What are iterators?",
    "How to work with std::function?",
    "What are lambda expressions?",
    "How to use std::bind?",
    "What are function objects?",

    "How to work with I/O streams?",
    "What are std::cin and std::cout?",
    "How to format output?",
    "What are stream manipulators?",
    "How to read and write files?",
    "What is std::fstream?",
    "How to work with binary files?",
    "What is stringstream?",
    "How to parse strings?",
    "What is data serialization?",
  ];

  static const List<String> middle = [
    "What is move semantics?",
    "How to use rvalue references?",
    "What is perfect forwarding?",
    "How does std::move work?",
    "What are universal references?",
    "How to use variadic templates?",
    "What are fold expressions?",
    "How does SFINAE work?",
    "What are concepts?",
    "How to use constexpr?",
    "What is if constexpr?",
    "How do template parameters work?",
    "What are template template parameters?",
    "How to use decltype and auto?",
    "What is trailing return type?",
    "How does structured binding work?",
    "What is std::initializer_list?",
    "How to use user-defined literals?",
    "What are attributes?",
    "How to work with noexcept?",
    "What are inline variables?",
    "How to use deduction guides?",
    "What is the spaceship operator?",
    "How do coroutines work?",
    "What are modules?",

    "How to create a thread in C++?",
    "What is std::thread?",
    "How to pass parameters to a thread?",
    "What is a race condition?",
    "How to use mutexes?",
    "What is std::mutex?",
    "How to work with std::lock_guard?",
    "What is std::unique_lock?",
    "How to use std::scoped_lock?",
    "What is a deadlock?",
    "How to avoid deadlock?",
    "What are condition variables?",
    "How to use std::future and std::promise?",
    "What is std::async?",
    "How to work with std::packaged_task?",
    "What are atomic operations?",
    "How to use std::atomic?",
    "What is memory order?",
    "How does thread_local work?",
    "What is a thread pool?",

    "How do function templates work?",
    "What is template specialization?",
    "How to use partial specialization?",
    "What are type traits?",
    "How to use std::enable_if?",
    "What is tag dispatch?",
    "How does CRTP work?",
    "What is SFINAE?",
    "How to use constexpr if?",
    "What are variadic templates?",
    "How to work with parameter packs?",
    "What are fold expressions?",
    "How to use template deduction?",
    "What are user-defined deduction guides?",
    "How does std::invoke work?",
    "What is std::apply?",
    "How to use std::visit?",
    "What are expression templates?",
    "How does policy-based design work?",
    "What are concepts?",

    "How to optimize C++ code?",
    "What are inline functions?",
    "How to use profiling?",
    "What is cache-friendly code?",
    "How to avoid false sharing?",
    "What is branch prediction?",
    "How to use SIMD instructions?",
    "What is vectorization?",
    "How to work with alignas?",
    "What are restrict pointers?",
    "How to use move semantics for optimization?",
    "What is small buffer optimization?",
    "How to avoid unnecessary copies?",
    "What is return value optimization?",
    "How does copy elision work?",

    "How to avoid buffer overflow?",
    "What is RAII?",
    "How to work with memory safely?",
    "What are smart pointers?",
    "How to avoid dangling pointers?",
    "What is const correctness?",
    "How to use noexcept?",
    "What is strong exception safety?",
    "How to handle exceptions?",
    "What is stack unwinding?",
    "How to work with threads safely?",
    "What is thread safety?",
    "How to avoid data races?",
    "What is deadlock prevention?",
    "How to work with files safely?",
    "What are secure coding guidelines?",
    "How to avoid integer overflow?",
    "What is type punning?",
    "How to use unions safely?",
    "What is undefined behavior?",
  ];

  static const List<String> senior = [
    "How to design a system in C++?",
    "What are the SOLID principles?",
    "How to implement dependency injection?",
    "What is inversion of control?",
    "How to use design patterns?",
    "What is the Factory Method?",
    "How to implement an Abstract Factory?",
    "What is the Builder pattern?",
    "How to use Singleton?",
    "What is the Prototype pattern?",
    "How to implement an Adapter?",
    "What is the Bridge pattern?",
    "How to use the Composite pattern?",
    "What is the Decorator pattern?",
    "How to implement a Facade?",
    "What is the Flyweight pattern?",
    "How to use the Proxy pattern?",
    "What is the Chain of Responsibility?",
    "How to implement the Command pattern?",
    "What is the Interpreter pattern?",
    "How to use the Iterator pattern?",
    "What is the Mediator pattern?",
    "How to implement the Memento pattern?",
    "What is the Observer pattern?",
    "How to use the State pattern?",

    "How to work with system calls?",
    "What is the POSIX API?",
    "How to use file descriptors?",
    "What are sockets?",
    "How to work with networking?",
    "What are epoll/kqueue?",
    "How to use mmap?",
    "What is shared memory?",
    "How to work with processes?",
    "What are fork/exec?",
    "How to use signals?",
    "What is a pipe?",
    "How to work with the terminal?",
    "What is a tty?",
    "How to use system limits?",
    "What is ulimit?",
    "How to work with the environment?",
    "What are environment variables?",
    "How to use locale?",
    "What is system time?",

    "How to write cross-platform code?",
    "What is conditional compilation?",
    "How to use the preprocessor?",
    "What is cmake?",
    "How to work with different compilers?",
    "What is ABI compatibility?",
    "How to account for endianness?",
    "What are alignment requirements?",
    "How to work with different type sizes?",
    "What are portable types?",
    "How to use libraries for different OSes?",
    "What is Boost?",
    "How to work with Qt?",
    "What is Poco?",
    "How to use cross-platform APIs?",

    "How to use a debugger?",
    "What is gdb?",
    "How to profile code?",
    "What is valgrind?",
    "How to use sanitizers?",
    "What is static analysis?",
    "How to set up CI/CD?",
    "What is automated testing?",
    "How to use Google Test?",
    "What are mocking frameworks?",
    "How to document code?",
    "What is Doxygen?",
    "How to use build systems?",
    "What is make?",
    "How to work with ninja?",
    "What are package managers?",
    "How to use conan?",
    "What is vcpkg?",
    "How to set up a codebase?",
    "What is a monorepo?",

    "What new features are in C++20?",
    "What are concepts?",
    "How to use ranges?",
    "What are coroutines?",
    "How do modules work?",
    "What's new in C++23?",
    "What proposals exist for C++26?",
    "What is reflection?",
    "How will metaclasses work?",
    "What is pattern matching?",
    "How to use the Networking TS?",
    "What are executors?",
    "How does a graphics library work?",
    "What is 2D/3D graphics?",
    "How to use C++ for machine learning?",
    "What is the TensorFlow C++ API?",
    "How to work with PyTorch C++?",
    "What is embedded C++?",
    "How to use C++ in IoT?",
    "What are trends in C++ development?",
  ];
}