class DevopsQuestionsEn {
  static const List<String> junior = [
    "What is DevOps and what are its main principles?",
    "What is the difference between DevOps and traditional approaches?",
    "What are the main goals of DevOps?",
    "What is CI/CD?",
    "How is DevOps related to Agile methodologies?",
    "What are the main stages of the DevOps lifecycle?",
    "What is Infrastructure as Code (IaC)?",
    "What benefits does IaC provide?",
    "What is containerization?",
    "What's the difference between virtual machines and containers?",
    "What is monitoring and why is it needed?",
    "What are the main metrics to monitor?",
    "What is logging?",
    "What types of logs exist?",
    "What is a version control system?",
    "Why is Git needed in DevOps?",
    "What are build artifacts?",
    "How to manage dependencies?",
    "What is an environment?",
    "What types of environments exist?",
    "What is deployment?",
    "What deployment strategies exist?",
    "What is a rollback?",
    "How to organize change rollback?",
    "What is configuration management?",
    "What tools are used for configuration management?",
    "What is container orchestration?",
    "Why is orchestration needed?",
    "What is cloud computing?",
    "What cloud service models exist?",

    "What is Git and how does it work?",
    "How to create a Git repository?",
    "How to commit changes?",
    "What are branches in Git?",
    "How to create and switch to a branch?",
    "How to merge branches?",
    "What is a merge conflict?",
    "How to resolve a conflict in Git?",
    "What is a pull request?",
    "How to create a pull request?",
    "What is code review?",
    "How to conduct code review?",
    "What are Git hooks?",
    "How to use pre-commit hooks?",
    "What is a .gitignore file?",
    "How to ignore files in Git?",
    "What is Git flow?",
    "What are the alternatives to Git flow?",
    "What is trunk-based development?",
    "How does GitHub work?",
    "How does GitLab work?",
    "What is Bitbucket?",
    "How to set up SSH keys for Git?",
    "What are submodules in Git?",
    "How to work with large files in Git?",

    "What are the main Linux commands to know?",
    "How to work with files and directories?",
    "What are file permissions in Linux?",
    "How to change permissions?",
    "How to work with processes?",
    "How to find and kill a process?",
    "What are system daemons?",
    "How to manage services?",
    "How to work with system logs?",
    "What is journalctl?",
    "How to configure networking in Linux?",
    "What is iptables?",
    "How to set up a firewall?",
    "How to work with package managers?",
    "What are apt and yum?",
    "How to install a package?",
    "How to update the system?",
    "What is cron?",
    "How to set up a scheduled job?",
    "How to write a bash script?",

    "What is Docker?",
    "How to install Docker?",
    "What is a Docker image?",
    "How to create a Docker image?",
    "What is a Docker container?",
    "How to run a container?",
    "What is a Dockerfile?",
    "How to write a Dockerfile?",
    "What instructions are available in a Dockerfile?",
    "What is Docker Hub?",
    "How to push an image to a registry?",
    "How to pull an image from a registry?",
    "What are Docker volumes?",
    "How to use volumes for data?",
    "What is a Docker network?",

    "What is Jenkins?",
    "How to install Jenkins?",
    "How to create a pipeline in Jenkins?",
    "What is a Jenkinsfile?",
    "How to write a declarative pipeline?",
    "What are GitHub Actions?",
    "How to create a workflow in GitHub Actions?",
    "What is GitLab CI?",
    "How to set up .gitlab-ci.yml?",
    "What are the typical pipeline stages?",
  ];

  static const List<String> middle = [
    "What are multi-stage builds?",
    "How to reduce Docker image size?",
    "What is Docker Compose?",
    "How to use docker-compose.yml?",
    "How to orchestrate multiple containers?",
    "What are health checks?",
    "How to set up health checks?",
    "What are resource limits?",
    "How to limit container resources?",
    "What is security scanning?",
    "How to scan images for vulnerabilities?",
    "What is a Docker registry?",
    "How to set up a private registry?",
    "What are image tagging strategies?",
    "How to version images?",
    "What is a container runtime?",
    "What's the difference between Docker and containerd?",
    "What is Podman?",
    "How is Podman different from Docker?",
    "What is Buildah?",

    "What is Kubernetes?",
    "What are the main Kubernetes concepts?",
    "What is a Pod?",
    "How to create a Pod?",
    "What is a Deployment?",
    "How to create a Deployment?",
    "What is a Service?",
    "What types of Services exist?",
    "What is a ConfigMap?",
    "How to use a ConfigMap?",
    "What is a Secret?",
    "How to store secrets securely?",
    "What is a Namespace?",
    "Why are Namespaces needed?",
    "What is an Ingress?",
    "How to configure Ingress?",
    "What is Helm?",
    "How to create a Helm chart?",
    "What is a StatefulSet?",
    "When to use a StatefulSet?",
    "What is a DaemonSet?",
    "When to use a DaemonSet?",
    "What are Job and CronJob?",
    "How to set up a scheduled job?",
    "What is the operator pattern?",

    "What is Terraform?",
    "How to install Terraform?",
    "What is HCL?",
    "How to write Terraform configuration?",
    "What is a provider in Terraform?",
    "How to use the AWS provider?",
    "What is state in Terraform?",
    "How to manage the state file?",
    "What is remote state?",
    "How to set up remote state?",
    "What are modules in Terraform?",
    "How to create a module?",
    "What is Ansible?",
    "How to write an Ansible playbook?",
    "What is inventory in Ansible?",
    "How to manage hosts?",
    "What are roles in Ansible?",
    "How to create a role?",
    "What is Packer?",
    "How to create an image with Packer?",

    "What is AWS?",
    "What are the main AWS services?",
    "What is EC2?",
    "How to create a virtual machine?",
    "What is S3?",
    "How to work with object storage?",
    "What is VPC?",
    "How to set up networking in AWS?",
    "What is IAM?",
    "How to manage access?",
    "What is Azure?",
    "What are the main Azure services?",
    "What is GCP?",
    "What are the main GCP services?",
    "What's the difference between cloud providers?",

    "What is Prometheus?",
    "How to set up Prometheus?",
    "What are metrics?",
    "What metrics to collect?",
    "What is Grafana?",
    "How to create a dashboard in Grafana?",
    "What is Alertmanager?",
    "How to set up alerts?",
    "What is the ELK Stack?",
    "How to set up log collection?",
    "What is Fluentd?",
    "How to use Fluentd for logs?",
    "What is Jaeger?",
    "How to set up distributed tracing?",
    "What is APM?",

    "What is security in DevOps?",
    "What is DevSecOps?",
    "How to integrate security into the pipeline?",
    "What is vulnerability scanning?",
    "How to scan images for vulnerabilities?",
    "What is secret management?",
    "How to use HashiCorp Vault?",
    "What are network policies?",
    "How to restrict network traffic?",
    "What are pod security policies?",
    "How to restrict pod privileges?",
    "What is RBAC?",
    "How to set up role-based access control?",
    "What is compliance as code?",
    "How to automate compliance?",
  ];

  static const List<String> senior = [
    "How to design a cloud-native architecture?",
    "What is microservices architecture?",
    "How to break a monolith into microservices?",
    "What is a service mesh?",
    "How to use Istio?",
    "What is serverless architecture?",
    "When to use serverless?",
    "What is event-driven architecture?",
    "How to design an event-driven system?",
    "What is the CQRS pattern?",
    "How to implement CQRS?",
    "What is disaster recovery?",
    "How to design a DR strategy?",
    "What is a multi-cloud strategy?",
    "How to work with multiple clouds?",
    "What is hybrid cloud?",
    "How to integrate on-prem and cloud?",
    "What is GitOps?",
    "How to implement the GitOps approach?",
    "What is infrastructure as software?",
    "How to use programmable infrastructure?",
    "What is chaos engineering?",
    "How to conduct chaos experiments?",
    "What is SRE?",
    "What's the difference between DevOps and SRE?",

    "How to set up auto-scaling in Kubernetes?",
    "What are HPA and VPA?",
    "How to set up horizontal pod autoscaling?",
    "What is cluster autoscaling?",
    "How to scale a cluster?",
    "What is service discovery?",
    "How does service discovery work in Kubernetes?",
    "What is etcd?",
    "How does etcd work in Kubernetes?",
    "What is CNI?",
    "How to choose a network plugin?",
    "What is CSI?",
    "How to work with persistent storage?",
    "What is the operator framework?",
    "How to create a custom operator?",
    "What is a service mesh?",
    "How to use Linkerd?",
    "What is mTLS?",
    "How to set up mutual TLS?",
    "What are admission controllers?",

    "How to build a multi-stage pipeline?",
    "What is pipeline as code?",
    "How to implement GitOps with ArgoCD?",
    "What is FluxCD?",
    "How to set up continuous deployment?",
    "What is blue-green deployment?",
    "How to implement blue-green?",
    "What is canary deployment?",
    "How to set up canary releases?",
    "What are feature flags?",
    "How to manage feature flags?",
    "What are deployment strategies?",
    "How to choose a deployment strategy?",
    "What is progressive delivery?",
    "How to implement progressive delivery?",

    "What is zero trust architecture?",
    "How to implement zero trust?",
    "What is security compliance?",
    "How to ensure compliance in the cloud?",
    "What are SOC 2, ISO 27001?",
    "How to prepare for an audit?",
    "What is threat modeling?",
    "How to conduct threat modeling?",
    "What is penetration testing?",
    "How to organize a pentest?",
    "What is security monitoring?",
    "How to set up a SIEM?",
    "What is a WAF?",
    "How to set up a web application firewall?",
    "What is CSPM?",

    "How to optimize cloud costs?",
    "What is FinOps?",
    "How to implement FinOps practices?",
    "How to monitor costs?",
    "What is resource optimization?",
    "How to optimize resource usage?",
    "What is performance testing?",
    "How to conduct load testing?",
    "What is capacity planning?",
    "How to plan capacity?",
    "What is observability?",
    "How to achieve full observability?",
    "What is distributed tracing?",
    "How to analyze performance issues?",
    "What is performance tuning?",

    "How to build a DevOps culture in an organization?",
    "What is the DevOps maturity model?",
    "How to assess DevOps maturity?",
    "How to measure DevOps effectiveness?",
    "What are DORA metrics?",
    "How to use DORA metrics?",
    "How to manage technical debt?",
    "How to organize incident management?",
    "What is postmortem analysis?",
    "How to conduct a blameless postmortem?",
  ];
}