class FlutterQuestionsEn {
  static const List<String> junior = [
    "What is Dart and how does it differ from other languages?",
    "What are the main data types in Dart?",
    "What is Null Safety in Dart?",
    "How to declare a variable that can be null?",
    "What's the difference between `final`, `const`, and `var`?",
    "What is `late` in Dart?",
    "How do lists (`List`) and sets (`Set`) work in Dart?",
    "What is a `Map` in Dart? Give an example.",
    "How do `async`/`await` and `Future` work?",
    "What is a `Stream` and how to use it?",
    "How to handle errors in Dart (try/catch/finally)?",
    "What is a `mixin` and how to use it?",
    "What's the difference between `==` and `===` in Dart?",
    "How do getters and setters (`get`/`set`) work?",
    "What is an `extension` in Dart? Give an example.",
    "How do generics work in Dart?",
    "What is the cascade operator (`..`) in Dart?",
    "How to use the spread operator (`...`) in Dart?",
    "What are collection if and collection for?",
    "How do named and optional function parameters work?",

    "What is Flutter and how does it work?",
    "How does Flutter differ from React Native?",
    "What is a Widget in Flutter?",
    "What types of widgets are there (Stateless vs Stateful)?",
    "How does `BuildContext` work?",
    "What are `MaterialApp` and `CupertinoApp`?",
    "How to create a new Flutter project?",
    "How to add dependencies to `pubspec.yaml`?",
    "What are Hot Reload and Hot Restart?",
    "How does the widget tree work?",
    "What is a `Key` in Flutter and why is it needed?",
    "How to pass data between screens (navigation)?",
    "What is `Navigator` and how to use it?",
    "How to pass data through `arguments`?",
    "How do `Route` and `PageRoute` work?",
    "What is `Scaffold` and what parts does it consist of?",
    "How to add AppBar, BottomNavigationBar, Drawer?",
    "How to work with `ListView.builder`?",
    "What is `GridView` and how to use it?",
    "How to create animations in Flutter?",
    "What is `Hero` animation?",
    "How to use `GestureDetector` and `InkWell`?",
    "How to work with forms and text fields (`TextField`)?",
    "What are `Form` and `FormField`?",
    "How to validate form input?",
    "How to use `MediaQuery`?",
    "What is `LayoutBuilder`?",
    "How do `Flex` and `Expanded` work?",
    "What is `AspectRatio`?",
    "How to use `Stack` and `Positioned`?",

    "What is State Management and why is it needed?",
    "What's the difference between `setState`, `InheritedWidget`, `Provider`?",
    "How does `setState` work?",
    "What is `Provider` and how to use it?",
    "How to pass data through `Provider`?",
    "What is `ChangeNotifier`?",
    "How does `Bloc` work?",
    "What is `Cubit` and how does it differ from `Bloc`?",
    "How to use `Riverpod`?",
    "What is `GetX` and what are its pros/cons?",
    "How does `Redux` work in Flutter?",
    "When to use global state vs local state?",
    "How to avoid unnecessary widget rebuilds?",
    "What are `ValueNotifier` and `ValueListenableBuilder`?",
    "How to cache data in the app?",
    "What is `InheritedWidget`?",
    "How does `InheritedModel` work?",
    "What is `ScopedModel`?",
    "How to use `MobX`?",
    "What is `Fish-Redux`?",

    "How to make an HTTP request in Flutter?",
    "What are `http` and `dio`?",
    "How to parse JSON in Dart?",
    "What are `json_serializable` and `freezed`?",
    "How to work with REST API?",
    "How to handle network errors?",
    "What is `WebSocket` and how to use it?",
    "How to download and save files?",
    "What are `SharedPreferences`?",
    "How to work with SQLite (using `sqflite`)?",
    "What is `Hive`?",
    "How to use `Firebase Realtime Database`?",
    "What is `Firestore`?",
    "How to work with `GraphQL`?",
    "What is `Isar`?",

    "How to test Flutter applications?",
    "What are `unit test`, `widget test`, `integration test`?",
    "How to use `mockito` for testing?",
    "How to debug a Flutter app?",
    "What are `Flutter DevTools`?",
    "How to measure app performance?",
    "How to avoid memory leaks?",
    "How to work with logs (`logger`, `debugPrint`)?",
    "How to test navigation?",
    "How to test `Bloc` or `Provider`?",
    "How to build APK/IPA?",
    "What are `Flavor`s and why are they needed?",
    "How to publish an app to Google Play/App Store?",
    "What is `Fastlane`?",
    "How to set up CI/CD for Flutter?",
  ];

  static const List<String> middle = [
    "How do isolates work in Dart and when to use them?",
    "Explain the difference between Zone, Future, and Stream in Dart",
    "How to implement caching using Stream in Dart?",
    "How do generators (sync*, async*) work in Dart?",
    "How to use metaprogramming in Dart?",
    "How to optimize Dart code performance?",
    "How do native extensions work in Dart?",
    "How to implement a custom operator in Dart?",
    "How to use reflection in Dart?",
    "How to work with binary data in Dart?",
    "What is FFI (Foreign Function Interface)?",
    "How to use dart:ffi?",
    "What are mixins and how to create your own?",
    "How do abstract classes work in Dart?",
    "What are sealed classes?",
    "How to use design patterns in Dart?",
    "What is dependency injection in Dart?",
    "How to implement a singleton in Dart?",
    "What are factory constructors?",
    "How to use typedef in Dart?",

    "How does the Flutter engine work under the hood?",
    "Explain the difference between Widget, Element, and RenderObject",
    "How does the composition mechanism work in Flutter?",
    "How to create a custom RenderObject?",
    "How does hit testing work in Flutter?",
    "How to implement a custom painter?",
    "How does the gesture system work in Flutter?",
    "How to implement complex animations using CustomPainter?",
    "How does the layout mechanism work in Flutter?",
    "How to optimize performance of complex lists?",
    "What are Slivers and CustomScrollView?",
    "How to use NestedScrollView?",
    "What is RepaintBoundary?",
    "How does ShaderMask work?",
    "What is BackdropFilter?",
    "How to use Transform?",
    "What are Hero animations?",
    "How to create custom page transitions?",
    "How to work with PlatformView?",
    "What is Texture?",
    "How to use Flutter for desktop?",
    "How to adapt an app for different platforms?",
    "What is Adaptive design?",
    "How to work with accessibility?",
    "What are semantics?",
    "How to test widget performance?",
    "What is PerformanceOverlay?",
    "How to use DevTools for profiling?",
    "What is Timeline?",
    "How to analyze jank?",

    "How to implement clean architecture in Flutter?",
    "How to organize a feature-first project structure?",
    "How to implement dependency injection without packages?",
    "How to work with domain-driven design in Flutter?",
    "How to implement ports and adapters architecture?",
    "How to organize a layered architecture?",
    "How to implement modular architecture?",
    "How to work with hexagonal architecture?",
    "How to organize testable architecture?",
    "How to implement event sourcing?",
    "How to implement undo/redo functionality in state management?",
    "How does the BLoC pattern work with multiple BLoCs?",
    "How to implement dependencies between states in Riverpod?",
    "How to test complex state management solutions?",
    "How to implement state persistence between sessions?",
    "How to work with websockets in state management?",
    "How to implement an offline-first approach?",
    "How to scale state management for large applications?",
    "How to implement state hydration?",
    "How to work with complex state machines?",
    "What is MVI architecture?",
    "How to implement Redux in Flutter?",
    "What is Flux architecture?",
    "How to use MVVM with Flutter?",
    "What is Clean Architecture with Flutter?",

    "How to profile Flutter app performance?",
    "How to optimize frame rate?",
    "How to work with memory leaks in Dart?",
    "How to reduce app size?",
    "How to optimize battery consumption?",
    "How to work with jank and stutter?",
    "How to implement lazy loading of resources?",
    "How to optimize image handling?",
    "How to work with native memory in Flutter?",
    "How to implement performance monitoring?",
    "What is Skia?",
    "How does Flutter rasterization work?",
    "How to optimize build times?",
    "What is shader compilation jank?",
    "How to use cached_network_image?",

    "How to implement plugins for Flutter?",
    "How to work with platform channels?",
    "How to integrate native code into Flutter?",
    "How to implement custom platform views?",
    "How to work with FFI (Foreign Function Interface)?",
    "How to implement cross-platform solutions?",
    "How to work with Flutter for web?",
    "How to implement a PWA with Flutter?",
    "How to work with Flutter in embedded systems?",
    "How to implement a custom engine for Flutter?",
  ];

  static const List<String> senior = [
    "How do you design architecture for large-scale Flutter applications?",
    "What strategies do you use to ensure application scalability?",
    "How to implement microservices architecture in a Flutter app?",
    "What approaches do you use for managing complex application states?",
    "How to integrate Flutter with existing native infrastructure?",
    "How to design a system to support A/B testing at all levels?",
    "What methods do you use to ensure codebase modularity?",
    "How to implement a feature flags system for managing functionality?",
    "How to organize cross-platform architecture for iOS/Android/Web/Desktop?",
    "What strategies do you apply for legacy code migration?",
    "How to design a system for international localization?",
    "What is design system architecture?",
    "How to organize a shared kernel between modules?",
    "What are bounded contexts in DDD?",
    "How to implement event-driven architecture?",
    "What is the CQRS pattern?",
    "How to design for horizontal scaling?",
    "What are clean code principles in Flutter?",
    "How to apply SOLID principles in Flutter?",
    "What is the dependency inversion principle?",
    "How to implement onion architecture?",
    "What is hexagonal architecture?",
    "How to organize feature slicing?",
    "What is vertical slice architecture?",
    "How to design for testability?",
    "What is contract testing?",
    "How to implement consumer-driven contracts?",
    "What is an anti-corruption layer?",
    "How to organize the domain layer?",
    "What is the application layer in clean architecture?",

    "How do you organize the code review process in a Flutter development team?",
    "What methodologies do you use for knowledge sharing within the team?",
    "How to build an architectural decision-making process?",
    "How to organize an effective CI/CD pipeline for Flutter projects?",
    "What strategies do you use for gradual adoption of new technologies?",
    "How to measure and improve code quality in the long term?",
    "What approaches do you use for technical debt management?",
    "How to organize the onboarding process for new developers in a project?",
    "What metrics do you track to assess project health?",
    "How to build collaboration between Flutter and native teams?",
    "How to conduct technical interviews for Flutter developers?",
    "What criteria do you use to evaluate developer levels?",
    "How to create a grading system for a Flutter team?",
    "How to motivate the team to learn new technologies?",
    "How to organize a mentorship process within the team?",
    "What is an engineering ladder?",
    "How to conduct developer performance reviews?",
    "How to manage conflicts in a technical team?",
    "How to build relationships with product managers?",
    "How to align technical and business requirements?",
    "How to assess technical risks?",
    "What is risk management in development?",
    "How to create technical documentation?",
    "What are ADRs (Architecture Decision Records)?",
    "How to maintain a company technical blog?",

    "How to implement an end-to-end security audit for a mobile application?",
    "What methods do you use to protect against reverse engineering?",
    "How to organize secure data storage at the application level?",
    "What approaches do you use for GDPR/CCPA compliance?",
    "How to implement security monitoring in production?",
    "What strategies do you apply for secure credential storage?",
    "How to organize secure communication between client and server?",
    "What methods do you use to protect against injection attacks?",
    "How to implement role-based access control on the client side?",
    "How to organize a security code review process?",
    "What is OWASP Mobile Top 10?",
    "How to protect an app from MITM attacks?",
    "What is certificate pinning?",
    "How to implement biometric authentication?",
    "What is a hardware-backed keystore?",
    "How to work with encrypted shared preferences?",
    "What is data encryption at rest?",
    "How to implement secure logging?",
    "What is RASP (Runtime Application Self-Protection)?",
    "How to organize pentesting for a mobile application?",

    "Which emerging technologies in the Flutter ecosystem do you consider promising?",
    "How do you evaluate Flutter's potential for new platforms?",
    "What approaches do you use for experimental feature development?",
    "How do you organize the process of researching new technologies?",
    "What methods do you apply for technical forecasting?",
    "How do you evaluate the technical feasibility of new ideas?",
    "What strategies do you use for gradual innovation adoption?",
    "How do you organize the contribution process to open-source Flutter?",
    "What approaches do you use to evaluate new state management solutions?",
    "How do you work with technical debt when implementing new technologies?",
    "What is Flutter Web and its limitations?",
    "How does Flutter for desktop work?",
    "What is the Flutter Embedding API?",
    "How to use Flutter in embedded devices?",
    "What is Flutter Fuchsia?",

    "How do you evaluate ROI from investments in Flutter?",
    "What metrics do you use to measure the success of a Flutter project?",
    "How to justify choosing Flutter to a client?",
    "How to evaluate the cost of ownership of a Flutter application?",
    "How to build a long-term development strategy for a Flutter team?",
    "How to align technical and business roadmaps?",
    "How to manage stakeholder expectations?",
    "How to conduct technical due diligence?",
    "What is a technology radar?",
    "How to create a company's technical strategy?",
  ];
}