class GitQuestionsEn {
  static const List<String> junior = [
    "What is Git and what is it used for?",
    "What's the difference between Git and GitHub?",
    "How to install and configure Git?",
    "How to check the Git version?",
    "How to configure username and email in Git?",
    "What is a repository in Git?",
    "How to create a new repository?",
    "How to clone an existing repository?",
    "What is the working directory?",
    "What is the staging area?",
    "What is a commit in Git?",
    "How to check repository status?",
    "How to add files to the staging area?",
    "How to make a commit?",
    "How to write a good commit message?",
    "How to view commit history?",
    "What is a commit hash?",
    "How to view changes in files?",
    "How to discard changes in the working directory?",
    "How to remove a file from Git?",
    "How to rename or move a file?",
    "What is a .gitignore file?",
    "How to ignore files in Git?",
    "What patterns can be used in .gitignore?",
    "How to view differences between commits?",
    "What is git diff?",
    "How to view a specific commit?",
    "How to find a commit by message?",
    "What is HEAD in Git?",
    "How to view changes in a specific file?",

    "What is a branch in Git?",
    "How to create a new branch?",
    "How to switch to another branch?",
    "How to create and switch to a branch in one command?",
    "How to view the list of branches?",
    "How to delete a branch?",
    "How to rename a branch?",
    "What is the main/master branch?",
    "How to view the last commit in a branch?",
    "How to compare two branches?",
    "What is merging in Git?",
    "How to merge branches?",
    "What is a fast-forward merge?",
    "What is a merge conflict?",
    "How to resolve a merge conflict?",
    "What is rebase?",
    "What's the difference between merge and rebase?",
    "When to use merge vs rebase?",
    "How to perform an interactive rebase?",
    "What is squashing commits?",
    "How to combine multiple commits into one?",
    "What is detached HEAD?",
    "How to exit detached HEAD state?",
    "How to create a branch from a specific commit?",
    "How to switch to the previous branch?",

    "What is a remote repository?",
    "How to add a remote repository?",
    "How to view the list of remote repositories?",
    "How to push changes to a remote repository?",
    "How to fetch changes from a remote repository?",
    "What's the difference between git pull and git fetch?",
    "How to update a local branch from remote?",
    "What is an upstream branch?",
    "How to set upstream for a branch?",
    "How to create a branch from a remote branch?",
    "How to delete a remote branch?",
    "How to update information about remote branches?",
    "What is git remote prune?",
    "How to rename a remote repository?",
    "How to delete a remote repository?",
    "What is forking a repository?",
    "How to create a pull request?",
    "How to check remote changes without merging?",
    "How to push a tag to a remote repository?",
    "How to clone a repository with a specific branch?",

    "How to discard changes in the working directory?",
    "How to remove a file from the staging area?",
    "How to undo the last commit?",
    "What's the difference between git reset and git revert?",
    "What is git reset --soft?",
    "What is git reset --mixed?",
    "What is git reset --hard?",
    "How to safely undo a commit?",
    "How to create a commit that undoes previous changes?",
    "How to temporarily save changes?",
    "What is git stash?",
    "How to apply saved changes?",
    "How to view the list of saved changes?",
    "How to delete saved changes?",
    "How to apply a specific stash?",

    "What is a tag in Git?",
    "How to create a tag?",
    "What's the difference between lightweight and annotated tags?",
    "How to view the list of tags?",
    "How to delete a tag?",
    "How to switch to a tag?",
    "How to create a tag for a previous commit?",
    "How to push tags to a remote repository?",
    "How to delete a tag from a remote repository?",
    "What is semantic versioning?",
  ];

  static const List<String> middle = [
    "How to view history in compact format?",
    "How to view history with branch graph?",
    "How to find a commit by file content?",
    "How to find a commit that modified a line?",
    "How to view change history of a specific file?",
    "How to view who last modified a line in a file?",
    "What is git blame?",
    "How to use git bisect?",
    "How to find a bug using binary search?",
    "How to view differences between branches?",
    "How to view which files were changed in a commit?",
    "How to create a patch from commits?",
    "How to apply a patch?",
    "What is cherry-pick?",
    "How to apply a specific commit from another branch?",
    "How to interactively add changes?",
    "What is git add -p?",
    "How to partially add changes from a file?",
    "How to view staged changes?",
    "How to discard changes in a specific file?",

    "What is merge strategy?",
    "What merge strategies exist?",
    "How to resolve complex conflicts?",
    "What are ours and theirs in conflict resolution?",
    "How to use merge tools?",
    "How to configure an external merge tool?",
    "What is rebase --interactive?",
    "How to reorder commits?",
    "How to edit a commit?",
    "How to split a commit into multiple?",
    "What is rebase --onto?",
    "How to move part of commits to another branch?",
    "What is an orphan branch?",
    "How to create a branch without history?",
    "How to track code movement between branches?",
    "What is git rerere?",
    "How to remember conflict resolutions?",
    "How to configure git rerere?",
    "What is subtree merge?",
    "How to merge projects with different histories?",

    "What are Git submodules?",
    "When to use submodules?",
    "How to add a submodule?",
    "How to clone a repository with submodules?",
    "How to update a submodule?",
    "How to make a commit in a submodule?",
    "How to manage submodule versions?",
    "What is the .gitmodules file?",
    "How to remove a submodule?",
    "How to move a submodule?",
    "What's the difference between submodule and subtree?",
    "What is Git subtree?",
    "How to use subtree?",
    "When to use subtree instead of submodule?",
    "How to convert a submodule to subtree?",

    "What are Git hooks?",
    "Where are Git hooks located?",
    "What types of hooks exist?",
    "How to create a custom hook?",
    "What is a pre-commit hook?",
    "How to use hooks for code validation?",
    "What is a pre-push hook?",
    "How to set up automatic testing?",
    "What is a commit-msg hook?",
    "How to validate commit messages?",
    "How to use a pre-rebase hook?",
    "What is a post-checkout hook?",
    "How to configure hooks for a team?",
    "What is the pre-commit framework?",
    "How to use Husky for Git hooks?",

    "How to configure Git settings?",
    "What's the difference between global and local configuration?",
    "How to set up aliases in Git?",
    "What useful aliases can be created?",
    "How to configure the default editor?",
    "How to configure diff tool?",
    "How to configure merge tool?",
    "What is the .gitconfig file?",
    "How to configure colors in Git?",
    "How to configure autocrlf?",
    "What is core.autocrlf?",
    "How to configure Git for different OS?",
    "How to configure SSH keys for Git?",
    "How to configure GPG commit signing?",
    "How to sign commits?",

    "How to clean up a repository?",
    "What is git gc?",
    "How to run garbage collection?",
    "What is git prune?",
    "How to find large files in history?",
    "How to remove a large file from history?",
    "What is BFG Repo-Cleaner?",
    "How to rewrite history?",
    "What is git filter-branch?",
    "How to modify commit history?",
    "How to merge multiple repositories?",
    "What is git shallow clone?",
    "How to clone a repository without full history?",
    "How to work with large repositories?",
    "What is Git LFS?",
  ];

  static const List<String> senior = [
    "What is Git workflow?",
    "What main Git workflows exist?",
    "What is GitFlow?",
    "How does GitFlow workflow work?",
    "What are feature branches in GitFlow?",
    "What are release branches?",
    "What are hotfix branches?",
    "What are alternatives to GitFlow?",
    "What is GitHub Flow?",
    "What's the difference between GitFlow and GitHub Flow?",
    "What is GitLab Flow?",
    "How to choose the right workflow?",
    "What is trunk-based development?",
    "How to implement continuous deployment with Git?",
    "What are feature flags?",
    "How to manage feature flags in Git?",
    "What is environment-based deployment?",
    "How to organize multi-environment setup?",
    "What are release strategies?",
    "How to implement blue-green deployment?",
    "What are canary releases?",
    "How to manage versions with Git?",
    "What is semantic versioning?",
    "How to automate releases?",
    "What are conventional commits?",

    "How to organize code review with Git?",
    "What is pull request workflow?",
    "How to conduct effective code reviews?",
    "What are protected branches?",
    "How to set up branch protection rules?",
    "What are required reviews?",
    "How to set up status checks?",
    "What are required status checks?",
    "How to integrate CI/CD with Git?",
    "What are GitHub Actions?",
    "How to set up automatic testing?",
    "How to manage access in Git?",
    "What is the Git permissions model?",
    "How to organize multi-team development?",
    "What is the fork and pull request model?",
    "How to work with contribution guidelines?",
    "What are CODEOWNERS?",
    "How to set up automatic reviewer assignment?",
    "What are draft pull requests?",
    "How to use templates for pull requests?",

    "How to ensure security in Git?",
    "What is secrets detection?",
    "How to prevent secrets from entering the repository?",
    "What are security pre-commit hooks?",
    "How to set up secret scanning?",
    "What is Git crypt?",
    "How to encrypt confidential files?",
    "What are signed commits?",
    "How to verify commit authenticity?",
    "What are verified commits?",
    "How to configure GPG signing?",
    "What is DCO (Developer Certificate of Origin)?",
    "How to comply with licensing requirements?",
    "What is license compliance?",
    "How to manage dependencies securely?",

    "How to analyze repository activity?",
    "What is Git analytics?",
    "How to measure team velocity?",
    "What is cycle time?",
    "How to track lead time?",
    "What is code churn?",
    "How to analyze technical debt?",
    "What is hotspot analysis?",
    "How to find problematic code areas?",
    "What is Git mining?",
    "How to use Git for retrospectives?",
    "What are contribution graphs?",
    "How to analyze collaboration patterns?",
    "What are network graphs?",
    "How to visualize repository history?",

    "How to integrate Git with CI/CD?",
    "What is GitOps?",
    "How to implement GitOps workflow?",
    "What is infrastructure as code with Git?",
    "How to manage configuration via Git?",
    "What is configuration drift detection?",
    "How to use Git for deployment?",
    "What is environment promotion?",
    "How to organize multi-stage deployment?",
    "What is Git for database migrations?",
    "How to manage DB migrations through Git?",
    "What is schema as code?",
    "How to use Git for documentation?",
    "What is docs as code?",
    "How to organize a monorepository?",

    "How to recover deleted commits?",
    "What is reflog?",
    "How to use reflog for recovery?",
    "How to fix a corrupted repository?",
    "What is fsck in Git?",
    "How to recover a corrupted repository?",
    "How to migrate between Git hosting platforms?",
    "How to transfer history between repositories?",
    "What is Git bundle?",
    "How to work with Git offline?",
  ];
}