class GoQuestionsEn {
  static const List<String> junior = [
    "What is Go and what are its main features?",
    "Who created Go and why?",
    "What is the philosophy of the Go language?",
    "How to install and set up a Go environment?",
    "What is the structure of a Go program?",
    "What is package main?",
    "How does the main() function work?",
    "What are the main data types in Go?",
    "How to declare a variable in Go?",
    "What's the difference between var and :=?",
    "What are zero values?",
    "How do integers work (int, int8, int16, int32, int64)?",
    "What are floating-point numbers (float32, float64)?",
    "How does the string type work?",
    "What are rune and byte?",
    "How does the bool type work?",
    "What are complex numbers (complex64, complex128)?",
    "What operators are available in Go?",
    "How do conditional operators (if-else) work?",
    "Can conditions be used without parentheses?",
    "How does switch work in Go?",
    "What loops are available in Go?",
    "How does the for loop work?",
    "Can while be used in Go?",
    "How to use break and continue?",
    "What is goto in Go?",
    "How does defer work?",
    "What are panic and recover?",
    "How to handle errors in Go?",
    "What is the error type?",

    "How to declare a function in Go?",
    "What are return values?",
    "How to return multiple values from a function?",
    "What are named return values?",
    "How to pass parameters to a function?",
    "What's the difference between pass by value and pass by reference?",
    "What are variadic functions?",
    "How to use ... in parameters?",
    "What are anonymous functions?",
    "How do closures work in Go?",
    "What is recursion in Go?",
    "How to declare a function as a type?",
    "What are function literals?",
    "How to pass a function as an argument?",
    "What are callback functions?",
    "How does the init() function work?",
    "What is the blank identifier (_)?",
    "How to ignore return values?",
    "What are built-in functions?",
    "What built-in functions are available in Go?",

    "What are arrays in Go?",
    "How to declare an array?",
    "What are slices?",
    "What's the difference between an array and a slice?",
    "How to create a slice?",
    "What is make() for slices?",
    "How does append() work?",
    "How to get the length and capacity of a slice?",
    "What is slice capacity?",
    "How does slice copying work?",
    "What are maps?",
    "How to create a map?",
    "How to add and remove elements from a map?",
    "How to check if a key exists in a map?",
    "What is a struct?",
    "How to declare a struct?",
    "How to create a struct instance?",
    "What are embedded structs?",
    "How does composition work in Go?",
    "What are struct tags?",
    "How to use JSON tags?",
    "What are interfaces?",
    "How to declare an interface?",
    "What is the empty interface (interface{})?",
    "How does type assertion work?",

    "What are packages in Go?",
    "How to import packages?",
    "What's the difference between different import styles?",
    "What is dot import?",
    "How to create a custom package?",
    "What is visibility in packages?",
    "What's the difference between uppercase and lowercase?",
    "What is the go.mod file?",
    "How do Go modules work?",
    "How to add a dependency?",
    "What is the vendor directory?",
    "How to update dependencies?",
    "What is the go.sum file?",
    "How to work with package versions?",
    "What is the replace directive in go.mod?",

    "How to use the fmt package?",
    "What is Println vs Printf?",
    "How to work with strings (strings package)?",
    "What does the strconv package do?",
    "How to convert a string to a number?",
    "How to work with time (time package)?",
    "What is duration in Go?",
    "How to use the os package?",
    "What is the flag package?",
    "How to work with command-line arguments?",
  ];

  static const List<String> middle = [
    "What are methods in Go?",
    "How to declare a method for a type?",
    "What's the difference between a function and a method?",
    "What are value and pointer receivers?",
    "When to use pointer receivers?",
    "What is interface satisfaction?",
    "How does duck typing work in Go?",
    "What is interface embedding?",
    "How does type switching work?",
    "What is type conversion?",
    "How to create custom types?",
    "What are type aliases?",
    "How do generics work in Go?",
    "What are type parameters?",
    "How to declare a generic function?",
    "What are constraints?",
    "How to use comparable and any?",
    "What are type sets?",
    "How to create a generic struct?",
    "What is type inference?",

    "What are goroutines?",
    "How to start a goroutine?",
    "What is the GMP model?",
    "How does the Go scheduler work?",
    "What are channels?",
    "How to create a channel?",
    "What's the difference between buffered and unbuffered channels?",
    "How to send and receive data from a channel?",
    "What is select?",
    "How does the default case in select work?",
    "What is range over channel?",
    "How to close a channel?",
    "How to check if a channel is closed?",
    "What is the sync package?",
    "How to use WaitGroup?",
    "What is a Mutex?",
    "What's the difference between Mutex and RWMutex?",
    "How does Once work?",
    "What is Cond?",
    "How to use Pool?",
    "What are atomic operations?",
    "How to use sync/atomic?",
    "What is context?",
    "How to use WithCancel, WithTimeout, WithDeadline?",
    "What is a race condition and how to detect it?",

    "How to work with JSON?",
    "What is encoding/json?",
    "How to serialize a struct to JSON?",
    "What are marshal and unmarshal?",
    "How to use struct tags for JSON?",
    "How to work with XML?",
    "What is encoding/xml?",
    "How to serialize to XML?",
    "What is YAML and how to work with it?",
    "How to use go-yaml?",
    "What is protobuf?",
    "How to work with gRPC in Go?",
    "What is database/sql?",
    "How to connect to a database?",
    "How to execute SQL queries?",
    "What is sqlx?",
    "How to work with transactions?",
    "What is connection pooling?",
    "How to use prepared statements?",
    "What are database migrations?",

    "How to write tests in Go?",
    "What is the testing package?",
    "How to run tests?",
    "What are table-driven tests?",
    "How to test private functions?",
    "What is testify?",
    "How to use assert and require?",
    "What is mock testing?",
    "How to use gomock?",
    "What are integration tests?",
    "How to test HTTP handlers?",
    "What is httptest?",
    "How to write benchmarks?",
    "What are benchmark tests?",
    "How to analyze performance?",

    "How to use pprof?",
    "What is CPU profiling?",
    "How to analyze memory?",
    "What is memory profiling?",
    "How to find memory leaks?",
    "What is escape analysis?",
    "How does the garbage collector work in Go?",
    "What is GC tuning?",
    "How to reduce allocations?",
    "What is sync.Pool and when to use it?",

    "How to create an HTTP server?",
    "What is net/http?",
    "How to work with HTTP handlers?",
    "What is middleware in Go?",
    "How to create a REST API?",
    "What is routing?",
    "How to use gorilla/mux?",
    "What is WebSocket in Go?",
    "How to create a TCP server?",
    "What is the net package?",
  ];

  static const List<String> senior = [
    "How to design Go applications?",
    "What is Clean Architecture in Go?",
    "How to implement Domain-Driven Design?",
    "What is Hexagonal Architecture?",
    "How to organize project structure?",
    "What is package organization?",
    "How to separate code into layers?",
    "What is dependency injection in Go?",
    "How to use wire for DI?",
    "What are design patterns in Go?",
    "How to implement Singleton?",
    "What is the Factory pattern?",
    "How to use the Builder pattern?",
    "What is the Strategy pattern?",
    "How to implement the Observer pattern?",
    "What is the Decorator pattern?",
    "How to use the Adapter pattern?",
    "What is the Facade pattern?",
    "How to implement the Command pattern?",
    "What is the Repository pattern?",
    "How to use the Service layer?",
    "What is CQRS in Go?",
    "How to implement Event Sourcing?",
    "What is microservice architecture?",
    "How to design microservices in Go?",

    "What is work stealing?",
    "How does the Go scheduler work?",
    "What is netpoller?",
    "How does I/O work in Go?",
    "What is non-blocking I/O?",
    "How to implement a worker pool?",
    "What is fan-out, fan-in?",
    "How to use the pipeline pattern?",
    "What is rate limiting?",
    "How to implement a circuit breaker?",
    "What is backpressure?",
    "How to handle overload?",
    "What is graceful shutdown?",
    "How to properly stop goroutines?",
    "What is context propagation?",
    "How to pass context across boundaries?",
    "What is tracing?",
    "How to implement distributed tracing?",
    "What is OpenTelemetry in Go?",
    "How to monitor goroutines?",

    "How to optimize Go applications?",
    "What is escape analysis?",
    "How to reduce allocations?",
    "What is stack vs heap?",
    "How does memory management work?",
    "What are GC pauses?",
    "How to configure the garbage collector?",
    "What is GODEBUG?",
    "How to use gctrace?",
    "What is inlining?",
    "How does the Go compiler work?",
    "What are compiler optimizations?",
    "How to use build tags?",
    "What is cross-compilation?",
    "How to reduce binary size?",

    "How to create a distributed system in Go?",
    "What is service discovery?",
    "How to use Consul?",
    "What is etcd?",
    "How to implement leader election?",
    "What are distributed locks?",
    "How to use Redis for distributed locks?",
    "What are consensus algorithms?",
    "How does Raft work?",
    "What are distributed transactions?",
    "How to implement the saga pattern?",
    "What is event-driven architecture?",
    "How to use message brokers?",
    "What is Kafka with Go?",
    "How to work with NATS?",

    "How to ensure security of Go applications?",
    "What is OWASP for Go?",
    "How to prevent SQL injection?",
    "What is XSS protection?",
    "How to implement CSRF protection?",
    "What is JWT in Go?",
    "How to work with OAuth2?",
    "What is the crypto package?",
    "How to use TLS?",
    "What is mTLS?",

    "How to set up CI/CD for Go?",
    "What is GoReleaser?",
    "How to create a Docker image for Go?",
    "What are multi-stage builds?",
    "How to reduce Docker image size?",
    "What is Kubernetes for Go applications?",
    "How to set up health checks?",
    "What are readiness and liveness probes?",
    "How to monitor Go applications?",
    "What is Prometheus for Go?",

    "What are Go best practices?",
    "What are Go code review comments?",
    "How to use golangci-lint?",
    "What is static analysis?",
    "What are trends in the Go community?",
  ];
}