class JavaQuestionsEn {
  static const List<String> junior = [
    "What is Java and what are its main features?",
    "What's the difference between JDK, JRE, and JVM?",
    "How does the JVM work?",
    "What is bytecode?",
    "How is a Java program compiled and run?",
    "What is the main method?",
    "What primitive data types are there in Java?",
    "What are reference data types?",
    "How to declare a variable in Java?",
    "What's the difference between int and Integer?",
    "What is autoboxing and unboxing?",
    "How do strings (String) work in Java?",
    "What's the difference between String, StringBuilder, and StringBuffer?",
    "What are arrays and how to work with them?",
    "How to declare and initialize an array?",
    "What are varargs?",
    "What operators are there in Java?",
    "How do conditional operators work (if-else, switch)?",
    "What loops are there in Java (for, while, do-while)?",
    "How to use break and continue?",
    "What is the ternary operator?",
    "How does the instanceof operator work?",
    "What is type casting?",
    "How to convert a string to a number?",
    "How to convert a number to a string?",
    "What is System.out.println?",
    "How to work with Scanner for input?",
    "What are comments in Java?",
    "What access modifiers are there in Java?",
    "What is Javadoc?",

    "What are classes and objects?",
    "How to create a class in Java?",
    "How to create an object of a class?",
    "What is a constructor?",
    "How do default constructors work?",
    "What is constructor overloading?",
    "What is the this keyword?",
    "What is inheritance in Java?",
    "How to use extends?",
    "What is the super keyword?",
    "How does method overriding work?",
    "What is polymorphism?",
    "What is encapsulation?",
    "How to implement getters and setters?",
    "What are abstract classes?",
    "How to declare an abstract method?",
    "What are interfaces?",
    "How to use implements?",
    "What's the difference between an abstract class and an interface?",
    "What are final classes and methods?",
    "How does the static keyword work?",
    "What are static methods and variables?",
    "What are static initialization blocks?",
    "What are inner classes?",
    "How to use anonymous classes?",

    "How to work with date and time?",
    "What is java.util.Date?",
    "How to use the java.time API?",
    "What are LocalDate, LocalTime, LocalDateTime?",
    "How to format dates?",
    "How to work with mathematical operations?",
    "What does the Math class do?",
    "How to generate random numbers?",
    "What is the Random class?",
    "How to work with big numbers?",
    "What are BigInteger and BigDecimal?",
    "How to compare objects?",
    "What are equals() and hashCode()?",
    "How does the toString() method work?",
    "What is the Comparable interface?",
    "How to use Comparator?",
    "What is the System class?",
    "How to work with the Runtime class?",
    "What is the Object class?",
    "What are the main methods of the Object class?",

    "What are collections in Java?",
    "What's the difference between Collection and Collections?",
    "What is the List interface?",
    "How to use ArrayList?",
    "How does LinkedList work?",
    "What's the difference between ArrayList and LinkedList?",
    "What is the Set interface?",
    "How to use HashSet?",
    "What is TreeSet?",
    "How does the Map interface work?",
    "How to use HashMap?",
    "What is TreeMap?",
    "How to iterate through collections?",
    "What is an Iterator?",
    "How to use the for-each loop?",

    "What are exceptions in Java?",
    "What is the exception hierarchy?",
    "What's the difference between checked and unchecked exceptions?",
    "How to handle exceptions?",
    "What is try-catch-finally?",
    "How to use multi-catch?",
    "What is try-with-resources?",
    "How to create a custom exception?",
    "When to use throws?",
    "What are Error and Exception?",
  ];

  static const List<String> middle = [
    "What are generics and why are they needed?",
    "How to declare a generic class?",
    "How to use generic methods?",
    "What are wildcards?",
    "What's the difference between <?>, <? extends T>, <? super T>?",
    "What is type erasure?",
    "How do annotations work?",
    "How to create a custom annotation?",
    "What is reflection?",
    "How to use java.lang.reflect?",
    "What are proxy objects?",
    "How does dynamic class creation work?",
    "What are enums and how to use them?",
    "How to add methods to an enum?",
    "What are functional interfaces?",
    "What are lambda expressions?",
    "How to use method references?",
    "What is the Stream API?",
    "How do intermediate and terminal operations work?",
    "What is Optional?",
    "How to use Optional to avoid NPE?",
    "What is the module system?",
    "How to work with JPMS?",
    "What is module-info.java?",
    "How to create a custom module?",

    "What are threads in Java?",
    "How to create a thread?",
    "What's the difference between Thread and Runnable?",
    "How to use ExecutorService?",
    "What is a ThreadPool?",
    "How do Future and Callable work?",
    "What is synchronized?",
    "How does volatile work?",
    "What is a race condition?",
    "How to avoid deadlock?",
    "What are monitors in Java?",
    "How to use wait(), notify(), notifyAll()?",
    "What is the java.util.concurrent package?",
    "How to use the Lock interface?",
    "What is ReentrantLock?",
    "How do ReadWriteLock work?",
    "What are atomic operations?",
    "How to use AtomicInteger?",
    "What is ConcurrentHashMap?",
    "How does CopyOnWriteArrayList work?",
    "What is BlockingQueue?",
    "How to use CountDownLatch?",
    "What is CyclicBarrier?",
    "How does Semaphore work?",
    "What is CompletableFuture?",

    "How does HashMap work internally?",
    "What is a hash function?",
    "How are collisions resolved in HashMap?",
    "What's the difference between HashMap and Hashtable?",
    "What is LinkedHashMap?",
    "How does TreeMap work?",
    "What is NavigableMap?",
    "How to use WeakHashMap?",
    "What is ConcurrentSkipListMap?",
    "How do concurrent collections work?",
    "What is CopyOnWriteArraySet?",
    "How to use PriorityQueue?",
    "What is the Deque interface?",
    "How does ArrayDeque work?",
    "What is the Stream API for collections?",

    "What are I/O streams?",
    "What's the difference between InputStream and OutputStream?",
    "How to work with files?",
    "What are FileReader and FileWriter?",
    "How to use BufferedReader?",
    "What is serialization?",
    "How to implement Serializable?",
    "What is transient?",
    "How does Externalizable work?",
    "What is NIO?",
    "What's the difference between IO and NIO?",
    "What are Channel and Buffer?",
    "How to use ByteBuffer?",
    "What is a Selector?",
    "How to work with Path and Files?",

    "How does the garbage collector work?",
    "What types of garbage collectors are there in Java?",
    "What's the difference between Serial, Parallel, G1, ZGC?",
    "What is heap memory?",
    "How is JVM memory structured?",
    "What are stack and heap?",
    "How to find memory leaks?",
    "How to use jconsole and jvisualvm?",
    "What is JMX?",
    "How to profile a Java application?",

    "How to work with JDBC?",
    "What is DriverManager?",
    "How to use Connection, Statement, ResultSet?",
    "What's the difference between Statement and PreparedStatement?",
    "What is CallableStatement?",
    "How to work with transactions?",
    "What are commit and rollback?",
    "How to use connection pooling?",
    "What is HikariCP?",
    "How to work with JPA?",
  ];

  static const List<String> senior = [
    "What is Clean Architecture?",
    "How to implement Hexagonal Architecture?",
    "What is DDD?",
    "How to divide a domain into subdomains?",
    "What is a bounded context?",
    "How to implement CQRS?",
    "What is Event Sourcing?",
    "How does Event-Driven Architecture work?",
    "What is microservice architecture?",
    "How to design microservices?",
    "What are design patterns?",
    "How to implement Singleton?",
    "What is the Factory Method?",
    "How to use Abstract Factory?",
    "What is the Builder pattern?",
    "How to implement Prototype?",
    "What is the Adapter pattern?",
    "How to use Decorator?",
    "What is the Facade pattern?",
    "How to implement Observer?",
    "What is the Strategy pattern?",
    "How to use the Template Method?",
    "What is the Chain of Responsibility?",
    "How to implement the Command pattern?",
    "What is the State pattern?",

    "What is the Spring Framework?",
    "How does the IoC container work?",
    "What is Dependency Injection?",
    "How to use Spring annotations?",
    "What is Spring Boot?",
    "How does autoconfiguration work?",
    "What is Spring MVC?",
    "How to create a REST API?",
    "What is Spring Data?",
    "How to work with Spring Data JPA?",
    "What is Spring Security?",
    "How to implement authentication?",
    "What is JWT in Spring Security?",
    "How does OAuth2 work in Spring?",
    "What is Spring Cloud?",
    "How to implement service discovery?",
    "What is a Circuit Breaker?",
    "How to use Hystrix?",
    "What is Spring Batch?",
    "How does Spring Integration work?",

    "How to optimize memory usage?",
    "What is escape analysis?",
    "How does JIT compilation work?",
    "What is JVM tuning?",
    "How to configure JVM parameters?",
    "What are -Xms, -Xmx, -XX:MaxMetaspaceSize?",
    "How to choose a garbage collector?",
    "When to use G1GC vs ZGC?",
    "How to optimize database operations?",
    "What is connection pooling?",
    "How to use caching?",
    "What is Spring Cache?",
    "How does Redis work with Java?",
    "What is Hazelcast?",
    "How to monitor performance?",

    "How to implement distributed transactions?",
    "What is the Saga pattern?",
    "How does Two-Phase Commit work?",
    "What is eventual consistency?",
    "How to implement idempotency?",
    "What is the circuit breaker pattern?",
    "How to use retry mechanisms?",
    "What is the bulkhead pattern?",
    "How to implement rate limiting?",
    "What is an API gateway?",
    "How does a service mesh work?",
    "What is Istio?",
    "How to use Kubernetes with Java?",
    "What is Docker for Java applications?",
    "How to set up health checks?",

    "How to secure a Java application?",
    "What is OWASP Top 10?",
    "How to prevent SQL injection?",
    "What is XSS and how to protect against it?",
    "How to implement CSRF protection?",
    "What are security headers?",
    "How to work with SSL/TLS?",
    "What is mTLS?",
    "How to implement secret management?",
    "What is Vault?",

    "How to set up CI/CD for a Java project?",
    "What are Maven/Gradle?",
    "How to create a multi-module project?",
    "How to use Jenkins for Java?",
    "What is GitLab CI/CD?",
    "How to set up automated testing?",
    "What is SonarQube?",
    "How to use JaCoCo for coverage?",
    "What is a Dockerfile for Java?",
    "How to create a Jib image?",

    "How to write unit tests?",
    "What is JUnit 5?",
    "How to use Mockito?",
    "What are TestContainers?",
    "How to test Spring applications?",
  ];
}