class JavascriptQuestionsEn {
  static const List<String> junior = [
    "What is JavaScript and where is it used?",
    "How to connect JavaScript to HTML?",
    "What are the main data types in JavaScript?",
    "What's the difference between let, const and var?",
    "What is hoisting in JavaScript?",
    "How do comparison operators (== and ===) work?",
    "What is strict mode (use strict)?",
    "How do conditional operators (if/else, switch) work?",
    "What loops are there in JavaScript (for, while, do while)?",
    "How do functions work in JavaScript?",
    "What are Function Declaration and Function Expression?",
    "How do arrow functions work?",
    "What are callback functions?",
    "How do array methods (map, filter, reduce) work?",
    "What are objects in JavaScript?",
    "How to work with objects (adding, removing properties)?",
    "What is JSON?",
    "How to convert an object to JSON and back?",
    "What is destructuring of objects and arrays?",
    "How does the spread operator (...) work?",
    "What are template literals?",
    "How do Set and Map work?",
    "What is Date and how to work with it?",
    "How to work with Math in JavaScript?",
    "What is try/catch/finally?",
    "How to create a custom exception?",
    "What are setTimeout and setInterval?",
    "How does the typeof operator work?",
    "What is NaN and how to check for it?",
    "How do the && and || operators work?",

    "What is the DOM?",
    "How to find an element on a page?",
    "How to change an element's text?",
    "How to change an element's styles?",
    "How to add/remove an element's class?",
    "How to create a new element and add it to the DOM?",
    "How to remove an element from the DOM?",
    "How to clone an element?",
    "What is the Event Loop in JavaScript?",
    "How to work with events (addEventListener)?",
    "What is event bubbling?",
    "How to stop event bubbling?",
    "What is event delegation?",
    "How to get data from a form?",
    "How to prevent default action?",
    "How to work with element attributes?",
    "What are data-attributes?",
    "How to get element dimensions?",
    "How to get an element's position on the page?",
    "How does window.getComputedStyle work?",

    "What is asynchronicity in JavaScript?",
    "How do callback functions work?",
    "What is a Promise?",
    "How to handle errors in Promises?",
    "What are async/await?",
    "How does try/catch work with async/await?",
    "What is the Fetch API?",
    "How to make a GET request with fetch?",
    "How to make a POST request with fetch?",
    "How to work with server response?",
    "What is XMLHttpRequest?",
    "What's the difference between fetch and XMLHttpRequest?",
    "What is WebSocket?",
    "How to work with localStorage?",
    "How to work with sessionStorage?",

    "What is prototypal inheritance?",
    "How to create an object?",
    "How to create an object constructor?",
    "What is 'this' in JavaScript?",
    "How do call, apply, bind work?",
    "How to create a class in ES6?",
    "What is class inheritance?",
    "How do static methods work?",
    "What are getters and setters?",
    "How to use private fields?",
    "What is encapsulation in JavaScript?",
    "What is polymorphism in JavaScript?",
    "How does instanceof work?",
    "What is Object.create()?",
    "How to check an object's type?",

    "How to get the current page URL?",
    "How to redirect the user to another page?",
    "How to refresh the page with JavaScript?",
    "How to open a new browser window?",
    "How to work with cookies?",
    "What are Web Workers?",
    "How to check if a browser supports a specific feature?",
    "How to detect the user's device?",
    "How to get the user's geolocation?",
    "How to work with the History API?",
    "What are Service Workers?",
    "How to check the user's online status?",
    "How to work with the Notification API?",
    "How to get browser information?",
    "How to work with the Fullscreen API?",
    "How to use the Clipboard API?",
    "How to work with the Drag and Drop API?",
    "What is the Intersection Observer API?",
    "How to use the Geolocation API?",
    "How to work with the Device Orientation API?",
  ];

  static const List<String> middle = [
    "What are closures?",
    "How do lexical environment and scope work?",
    "What is currying?",
    "How do higher-order functions work?",
    "What is memoization?",
    "How to implement debounce and throttle?",
    "What is IIFE?",
    "How do generators work?",
    "What is Symbol and what is it used for?",
    "How do Proxy and Reflect work?",
    "What are WeakMap and WeakSet?",
    "How to use the Intl API?",
    "What is BigInt?",
    "How to work with TypedArrays?",
    "What is ArrayBuffer?",
    "How to use Atomics?",
    "What is SharedArrayBuffer?",
    "How do iterators work?",
    "What are generators?",
    "How to use async generators?",
    "What is Tail Call Optimization?",
    "How does the Event Loop work?",
    "What are microtasks and macrotasks?",
    "How does requestAnimationFrame work?",
    "What is WebAssembly?",

    "How to work with multiple Promises simultaneously?",
    "What is Promise.all?",
    "How to use Promise.race?",
    "What is Promise.allSettled?",
    "How to cancel a fetch request?",
    "How to implement retry on error?",
    "How to work with WebSockets?",
    "What is Socket.IO?",
    "How to use Server-Sent Events?",
    "What is GraphQL and how to work with it?",
    "How to work with REST API?",
    "What is CORS and how to configure it?",
    "How to work with JWT?",
    "What is OAuth and how to implement it?",
    "How to upload files to the server?",
    "How to implement upload progress?",
    "How to work with WebRTC?",
    "What is WebSocket and how to use it?",
    "How to implement long polling?",
    "What are Server-Sent Events?",

    "How to work with IndexedDB?",
    "What is WebSQL?",
    "How to use localStorage with expiration?",
    "How to implement data caching?",
    "What is PWA and how to create it?",
    "How to work with the File API?",
    "How to read files on the client?",
    "How to work with Blob?",
    "What is the Streams API?",
    "How to work with FormData?",
    "How to serialize and deserialize data?",
    "What are data structures in JavaScript?",
    "How to implement stack and queue?",
    "How to work with tree data structures?",
    "What are sorting algorithms in JavaScript?",

    "How to write unit tests in JavaScript?",
    "What is Jest?",
    "How to use Mocha and Chai?",
    "What are test doubles (mocks, stubs, spies)?",
    "How to test asynchronous code?",
    "What is end-to-end testing?",
    "How to use Cypress?",
    "What is Puppeteer?",
    "How to set up a linter (ESLint)?",
    "What is Prettier?",
    "How to use Babel?",
    "What is Webpack?",
    "How to set up project bundling?",
    "What is tree shaking?",
    "How to use npm/yarn?",
    "What is package.json?",
    "How to work with modules (ES modules)?",
    "What is CommonJS?",
    "How to use TypeScript?",
    "What is JSDoc?",

    "What is XSS and how to prevent it?",
    "How to protect against CSRF?",
    "What is CORS and how to configure it?",
    "How to safely work with user input?",
    "What is Content Security Policy?",
    "How to protect user data?",
    "What is Same Origin Policy?",
    "How to securely store tokens?",
    "What is JWT and how to work with it?",
    "How to implement authentication?",
    "What is OAuth 2.0?",
    "How to work with HTTPS?",
    "What are Secure Cookies?",
    "How to protect against Clickjacking?",
    "What is Subresource Integrity?",
    "How to protect against MITM attacks?",
    "What is HSTS?",
    "How to implement rate limiting?",
    "What are secure HTTP headers?",
    "How to conduct security audits?",
  ];

  static const List<String> senior = [
    "How to design application architecture?",
    "What are design patterns?",
    "How to implement MVC?",
    "What is MVVM?",
    "How to use Flux?",
    "What is Redux?",
    "How to implement unidirectional data flow?",
    "What is Clean Architecture?",
    "How to organize modular architecture?",
    "What are microservices?",
    "How to design APIs?",
    "What is RESTful API?",
    "How to implement GraphQL API?",
    "What is Serverless architecture?",
    "How to work with Event-Driven architecture?",
    "What is CQRS?",
    "How to implement Event Sourcing?",
    "What is Domain-Driven Design?",
    "How to organize caching?",
    "What are cache invalidation strategies?",
    "How to design for scalability?",
    "What is horizontal scaling?",
    "How to implement load balancing?",
    "What are fault tolerance patterns?",
    "How to design for high availability?",

    "How to profile a JavaScript application?",
    "What are Chrome DevTools?",
    "How to analyze performance?",
    "How to optimize page loading?",
    "What is Critical Rendering Path?",
    "How to optimize rendering?",
    "What is Virtual DOM?",
    "How does Shadow DOM work?",
    "What is lazy loading?",
    "How to implement code splitting?",
    "How to optimize memory usage?",
    "What are memory leaks?",
    "How to use WeakMap and WeakSet?",
    "How to optimize DOM manipulation?",
    "What are batch updates?",
    "How to use requestAnimationFrame?",
    "What are Web Workers?",
    "How to use Service Workers for caching?",
    "How to optimize network requests?",
    "What is HTTP/2 and how to use it?",

    "How does the JavaScript engine work?",
    "What is JIT compilation?",
    "How does garbage collection work?",
    "What is the memory heap?",
    "How does the call stack work?",
    "What is the event loop?",
    "How do microtasks and macrotasks work?",
    "What is WebAssembly?",
    "How to use WASM in JavaScript?",
    "What is SIMD in JavaScript?",
    "How to work with multithreading?",
    "What is SharedArrayBuffer?",
    "How to use Atomics?",
    "What are Web Components?",
    "How to create custom elements?",
    "What is Shadow DOM?",
    "How to use HTML templates?",
    "What is WebGL?",
    "How to work with the Canvas API?",
    "What is the Web Audio API?",

    "How to organize the development process?",
    "What are Agile methodologies?",
    "How to conduct code reviews?",
    "What is pair programming?",
    "How to organize CI/CD?",
    "What is continuous integration?",
    "How to set up automated testing?",
    "What is trunk-based development?",
    "How to manage technical debt?",
    "What is technical design?",
    "How to conduct architectural reviews?",
    "What are ADRs (Architecture Decision Records)?",
    "How to mentor junior developers?",
    "What is a mentorship program?",
    "How to organize knowledge sharing?",
    "What is engineering culture?",
    "How to conduct technical interviews?",
    "How to estimate task complexity?",
    "What are DORA metrics?",
    "How to measure team effectiveness?",

    "What are the new features in ECMAScript?",
    "What are ES6 modules?",
    "How does top-level await work?",
    "What's new in ES2022?",
    "What proposals are at the proposal stage?",
    "What are Decorators?",
    "How does Pattern Matching work?",
    "What is the Pipeline Operator?",
    "How to use the Temporal API?",
    "What are Records and Tuples?",
    "How does WebGPU work?",
    "What is WebTransport?",
    "How to use WebCodecs?",
    "What is WebNN?",
    "What are trends in web development?",
  ];
}