class KotlinQuestionsEn {
  static const List<String> junior = [
    "What is Kotlin and how does it differ from Java?",
    "What are the main data types in Kotlin?",
    "How to declare a variable in Kotlin (val vs var)?",
    "What is Null Safety in Kotlin?",
    "How does the safe call operator (?.) work?",
    "What is the Elvis operator (?:) in Kotlin?",
    "How does the !! operator work in Kotlin?",
    "What string templates are available in Kotlin?",
    "How do conditional expressions if and when work?",
    "What loops are there in Kotlin (for, while, do-while)?",
    "How does range work in Kotlin (.., until, downTo)?",
    "What is smart cast in Kotlin?",
    "How to declare and use an array in Kotlin?",
    "How do collections work in Kotlin (List, Set, Map)?",
    "What's the difference between List and Array?",
    "What are immutable and mutable collections?",
    "How do higher-order functions work?",
    "What are lambda expressions in Kotlin?",
    "How to use extension functions?",
    "What are infix functions?",
    "How do operator overloading work?",
    "What is a data class and how does it differ from a regular class?",
    "How does destructuring work?",
    "What is a sealed class?",
    "How to use enum class?",
    "What is an object declaration?",
    "How does a companion object work?",
    "What are inline classes?",
    "How to use type aliases?",
    "What are reified generics?",

    "What visibility modifiers are there in Kotlin?",
    "How does inheritance work in Kotlin?",
    "What are abstract classes?",
    "How do interfaces work in Kotlin?",
    "What is delegation in Kotlin?",
    "How to use property delegation?",
    "What are lazy and observable properties?",
    "How do lateinit properties work?",
    "What are primary and secondary constructors?",
    "How to use init blocks?",
    "What are inner classes?",
    "How do nested classes work?",
    "What are anonymous classes?",
    "How to use generics in Kotlin?",
    "What is variance (in, out) in generics?",
    "How does 'where' work for generics?",
    "What are reified type parameters?",
    "How to use annotations in Kotlin?",
    "What is reflection in Kotlin?",
    "How to work with KClass and KFunction?",

    "What are pure functions?",
    "How do higher-order functions work?",
    "What are lambda expressions?",
    "How to use anonymous functions?",
    "What are function references?",
    "How do standard functions let, run, with, apply, also work?",
    "What is a sequence in Kotlin?",
    "How do map, filter, reduce operators work?",
    "What are tailrec functions?",
    "How to use coroutines at a basic level?",
    "What are suspend functions?",
    "How does flow work in Kotlin?",
    "What is a channel in Kotlin?",
    "How to use select expression?",
    "What are context receivers?",

    "How to create an Activity in Kotlin?",
    "What are ViewBinding and DataBinding?",
    "How to work with RecyclerView in Kotlin?",
    "What is ViewModel in Android?",
    "How to use LiveData?",
    "What are Lifecycle-aware components?",
    "How to work with Room in Kotlin?",
    "What is WorkManager?",
    "How to use SharedPreferences?",
    "What is Intent and how to use it?",
    "How to work with Fragments?",
    "What is Navigation Component?",
    "How to use Retrofit in Kotlin?",
    "What is OkHttp?",
    "How to parse JSON in Kotlin?",
    "What are Moshi and Gson?",
    "How to work with permissions in Android?",
    "What is BroadcastReceiver?",
    "How to use Services in Android?",
    "What is ContentProvider?",

    "How to write unit tests in Kotlin?",
    "What is JUnit in Kotlin?",
    "How to use Mockito in Kotlin?",
    "What are Espresso tests?",
    "How to test ViewModel?",
    "What are Instrumentation tests?",
    "How to debug Kotlin code?",
    "What is Logcat and how to use it?",
    "How to work with breakpoints?",
    "What is profiling in Android Studio?",
    "How to measure application performance?",
    "What is StrictMode?",
    "How to test coroutines?",
    "What is MockK?",
    "How to test flows?",
  ];

  static const List<String> middle = [
    "How do inline functions work in Kotlin?",
    "What are reified type parameters?",
    "How to use context receivers?",
    "What are contravariance and covariance?",
    "How does star projection (*) work?",
    "What is DSL in Kotlin?",
    "How to create your own DSL?",
    "What are annotations and how to create them?",
    "How to use reflection for class analysis?",
    "What is KAPT and how does it work?",
    "How to use Kotlin Poet?",
    "What are contracts in Kotlin?",
    "How do crossinline and noinline inlining work?",
    "What are context functions?",
    "How to use sealed interfaces?",
    "What is a value class?",
    "How do multi-platform projects work?",
    "What is the expect/actual mechanism?",
    "How to use Kotlin/Native?",
    "What is Kotlin/JS?",
    "How does Kotlin Serialization work?",
    "What are context parameters?",
    "How to use context lambdas?",
    "What are context classes?",
    "How does contextual programming work?",

    "How does interface delegation work?",
    "What is property delegation?",
    "How to create your own property delegate?",
    "What are lazy and observable properties?",
    "How does lateinit work?",
    "What are type-safe builders?",
    "How to create a type-safe builder?",
    "What is composition vs inheritance?",
    "How to use the Decorator pattern?",
    "What is the Strategy pattern?",
    "How to implement the Observer pattern?",
    "What is the Factory pattern?",
    "How to use the Singleton pattern?",
    "What is the Adapter pattern?",
    "How to implement the Facade pattern?",
    "What is the Proxy pattern?",
    "How to use the Command pattern?",
    "What is the State pattern?",
    "How to implement the Visitor pattern?",
    "What is the Builder pattern?",

    "How does the dispatcher work in coroutines?",
    "What are Dispatchers.IO, Main, Default?",
    "How to create your own dispatcher?",
    "What is CoroutineScope?",
    "How does SupervisorJob work?",
    "What is CoroutineContext?",
    "How to combine contexts?",
    "What are async/await?",
    "How does withContext work?",
    "What is structured concurrency?",
    "How to handle exceptions in coroutines?",
    "What is CoroutineExceptionHandler?",
    "How to cancel coroutines?",
    "What are cancel and join?",
    "How does timeout work?",
    "What is Flow and how does it differ from Channel?",
    "How to use StateFlow and SharedFlow?",
    "What are cold and hot streams?",
    "How to transform Flow?",
    "What are flow operators (map, filter, etc)?",

    "How does Dagger Hilt work?",
    "What is dependency injection?",
    "How to create a multi-module application?",
    "What are dynamic feature modules?",
    "How does Navigation Component work?",
    "What are deep links?",
    "How to use ViewModel with SavedState?",
    "What is DataStore?",
    "How to work with Room and Flow?",
    "What is Paging Library?",
    "How to use WorkManager with coroutines?",
    "What is Compose and how to use it?",
    "How to test Compose UI?",
    "What are side effects in Compose?",
    "How to use ViewModel in Compose?",
    "What is state hoisting?",
    "How to work with CameraX?",
    "What is ML Kit?",
    "How to use Biometric API?",
    "What are App Bundles?",

    "How to test coroutines?",
    "What is TestCoroutineDispatcher?",
    "How to mock suspend functions?",
    "What is Turbine for testing Flow?",
    "How to test ViewModel with coroutines?",
    "What is UI Automator?",
    "How to test Navigation Component?",
    "What is hermetic testing?",
    "How to use Fake implementations?",
    "What is dependency injection for testing?",
    "How to measure code coverage?",
    "What is mutation testing?",
    "How to use static analysis tools?",
    "What is Detekt?",
    "How to set up CI/CD for Android?",
  ];

  static const List<String> senior = [
    "How to design clean architecture?",
    "What is domain-driven design?",
    "How to implement hexagonal architecture?",
    "What are ports and adapters?",
    "How to organize feature modules?",
    "What is the dependency rule principle?",
    "How to implement onion architecture?",
    "What is event sourcing?",
    "How to work with CQRS?",
    "How to design microservices?",
    "What are bounded contexts?",
    "How to implement modular monolith?",
    "What are vertical slices?",
    "How to organize a shared kernel?",
    "What is an anti-corruption layer?",
    "How to design for multi-platform?",
    "What is MVI architecture?",
    "How to implement Redux?",
    "What is Elm architecture?",
    "How to work with unidirectional data flow?",
    "What is a state machine?",
    "How to implement feature flags?",
    "What is A/B testing architecture?",
    "How to design for scalability?",
    "What are fault-tolerant systems?",

    "How to profile an Android application?",
    "What is Systrace?",
    "How to use Android Profiler?",
    "How to optimize application startup?",
    "What are cold/warm/hot start?",
    "How to reduce APK size?",
    "What are ProGuard and R8?",
    "How to work with native memory?",
    "What are memory leaks?",
    "How to use LeakCanary?",
    "How to optimize UI performance?",
    "What is jank and how to fix it?",
    "How to work with overdraw?",
    "What is GPU rendering profiling?",
    "How to optimize network operations?",
    "What are HTTP/2 and QUIC?",
    "How to cache data efficiently?",
    "What is stale-while-revalidate?",
    "How to optimize database operations?",
    "What is WAL mode in SQLite?",

    "How to implement secure storage?",
    "What is Android Keystore?",
    "How to work with biometric authentication?",
    "What is hardware-backed security?",
    "How to protect data in transit?",
    "What is certificate pinning?",
    "How to implement secure communication?",
    "What is TLS 1.3?",
    "How to protect APIs?",
    "What are OAuth 2.0 and OpenID Connect?",
    "How to implement role-based access control?",
    "What is attribute-based access control?",
    "How to protect against reverse engineering?",
    "What is obfuscation?",
    "How to use native code for security?",
    "What is RASP (Runtime Application Self-Protection)?",
    "How to implement secure logging?",
    "What is GDPR compliance?",
    "How to work with PII data?",
    "What is the data minimization principle?",

    "How to organize a code review process?",
    "What is pair programming?",
    "How to conduct technical interviews?",
    "What is an engineering ladder?",
    "How to mentor junior developers?",
    "What is a mentorship program?",
    "How to organize knowledge sharing?",
    "What are tech talks?",
    "How to conduct architectural reviews?",
    "What are ADRs (Architecture Decision Records)?",
    "How to manage technical debt?",
    "What is tech debt assessment?",
    "How to organize a CI/CD pipeline?",
    "What is trunk-based development?",
    "How to implement feature flags management?",
    "What are canary releases?",
    "How to organize incident management?",
    "What is postmortem analysis?",
    "How to measure engineering metrics?",
    "What are DORA metrics?",

    "What are the new features in Kotlin?",
    "What is Kotlin Multiplatform?",
    "How does Kotlin/Wasm work?",
    "What's new in Android development?",
    "How does Jetpack Compose work under the hood?",
    "What is declarative UI?",
    "How does Skia work in Android?",
    "What's new in Gradle?",
    "How does configuration cache work?",
    "What are convention plugins?",
    "How to use Kotlin in backend?",
    "What is Ktor?",
    "How does the Kotlin/Native memory model work?",
    "What is the new memory manager?",
    "What are trends in mobile development?",
  ];
}