class PhpQuestionsEn {
  static const List<String> junior = [
    "What is PHP and what is it used for?",
    "What's the difference between PHP and other web development languages?",
    "How to install and configure PHP?",
    "What is a web server and how does PHP interact with it?",
    "How to create your first PHP script?",
    "What is the basic syntax of PHP?",
    "What are the <?php ?> tags and when to use them?",
    "How to use echo and print for output?",
    "What's the difference between echo and print?",
    "What data types are there in PHP?",
    "What are scalar data types?",
    "How do integers work in PHP?",
    "How do floating-point numbers work?",
    "What are strings in PHP?",
    "How to use single and double quotes?",
    "What are boolean values?",
    "How does the null type work?",
    "What are arrays in PHP?",
    "How to declare an array?",
    "What's the difference between indexed and associative arrays?",
    "What are multidimensional arrays?",
    "How to declare a constant in PHP?",
    "What are define() and const?",
    "What's the difference between define() and const?",
    "How do variables work in PHP?",
    "What are variable variables?",
    "How to use superglobal arrays?",
    "What are _GET, _POST, _REQUEST?",
    "How does _SERVER work?",
    "What are _SESSION and _COOKIE?",

    "What arithmetic operators are there in PHP?",
    "How do comparison operators work?",
    "What's the difference between == and ===?",
    "What are assignment operators?",
    "How do increment and decrement work?",
    "What are logical operators?",
    "How to use &&, ||, !?",
    "What are string operators?",
    "How does string concatenation work?",
    "How do if-else conditional operators work?",
    "What is the alternative syntax for if?",
    "How does switch-case work?",
    "What loops are there in PHP?",
    "How does the for loop work?",
    "How does the while loop work?",
    "How does the do-while loop work?",
    "How does the foreach loop work?",
    "What's the difference between foreach and for?",
    "How to use break and continue?",
    "What is the match expression?",
    "How to use the ternary operator?",
    "What is the null coalescing operator??",
    "How to use the ?: operator?",
    "What is the spaceship operator <=>?",
    "How does the null coalescing assignment operator ??? work?",

    "How to declare a function in PHP?",
    "How to call a function?",
    "How to pass parameters to a function?",
    "What are return values?",
    "How to specify return type?",
    "What are typed parameters?",
    "How to make a parameter optional?",
    "What are default parameter values?",
    "What are variadic functions?",
    "How to use ... in parameters?",
    "What are anonymous functions?",
    "How to create an anonymous function?",
    "What are closures?",
    "How to use 'use' with closures?",
    "What are arrow functions?",
    "How to create an arrow function?",
    "What are callback functions?",
    "How to pass a function as an argument?",
    "What are built-in PHP functions?",
    "What are the main built-in functions?",

    "How to find string length?",
    "How to concatenate strings?",
    "How to split a string into an array?",
    "What are explode() and implode()?",
    "How to find a substring in a string?",
    "How to replace part of a string?",
    "How to change string case?",
    "How to remove whitespace from a string?",
    "How to get the number of array elements?",
    "How to add an element to an array?",
    "How to remove an element from an array?",
    "How to find an element in an array?",
    "How to sort an array?",
    "How to iterate through an array?",
    "What are array_map, array_filter, array_reduce?",

    "How to create an HTML form?",
    "How to process form data in PHP?",
    "What's the difference between GET and POST?",
    "How to validate form data?",
    "How to protect against XSS attacks?",
    "What is htmlspecialchars()?",
    "How to upload a file to the server?",
    "What is _FILES?",
    "How to work with uploaded files?",
    "What is move_uploaded_file()?",
  ];

  static const List<String> middle = [
    "What are classes and objects in PHP?",
    "How to create a class?",
    "How to create an object of a class?",
    "What is a constructor?",
    "How does __construct() work?",
    "What is a destructor?",
    "How does __destruct() work?",
    "What are access modifiers?",
    "What's the difference between public, private, protected?",
    "What is inheritance?",
    "How to use extends?",
    "What is parent::?",
    "What is polymorphism?",
    "How does method overriding work?",
    "What are abstract classes?",
    "How to create an abstract class?",
    "What are interfaces?",
    "How to use implements?",
    "What's the difference between an abstract class and an interface?",
    "What are traits?",
    "How to use traits?",
    "What are static methods and properties?",
    "How to use static?",
    "What are self:: and static::?",
    "What are magic methods?",

    "What are namespaces?",
    "How to create a namespace?",
    "How to use 'use' for import?",
    "What is autoloading?",
    "How does spl_autoload_register() work?",
    "What is Composer?",
    "How to install Composer?",
    "What is composer.json?",
    "How to use Packagist?",
    "What are PSR standards?",
    "What PSR standards exist?",
    "What are exceptions?",
    "How to use try-catch?",
    "How to create a custom exception?",
    "What are generators?",
    "How to use yield?",
    "What are attributes?",
    "How to use attributes?",
    "What are enums?",
    "How to create an enum?",

    "How to connect to a database?",
    "What is PDO?",
    "How to use PDO for MySQL?",
    "What are prepared statements?",
    "How to use prepare() and execute()?",
    "What is the advantage of prepared statements?",
    "How to execute a SELECT query?",
    "How to execute an INSERT query?",
    "How to execute an UPDATE query?",
    "How to execute a DELETE query?",
    "What are transactions?",
    "How to use beginTransaction(), commit(), rollback()?",
    "What is ORM?",
    "What is Eloquent ORM?",
    "How to use Eloquent?",
    "What are database migrations?",
    "How to create a migration?",
    "What is Query Builder?",
    "How to use Query Builder?",
    "What is Redis and how to work with it?",

    "What are SQL injections?",
    "How to protect against SQL injections?",
    "What are XSS attacks?",
    "How to protect against XSS?",
    "What are CSRF attacks?",
    "How to protect against CSRF?",
    "What are session attacks?",
    "How to protect sessions?",
    "What is password hashing?",
    "How to use password_hash() and password_verify()?",
    "What are JWT tokens?",
    "How to work with JWT in PHP?",
    "What is OAuth?",
    "How to implement OAuth authentication?",
    "What is CORS and how to configure it?",

    "How to optimize PHP code?",
    "What is OPcache?",
    "How to configure OPcache?",
    "What is caching?",
    "How to use Memcached?",
    "How to use Redis for caching?",
    "What is APCu?",
    "How to use APCu?",
    "What is PHP profiling?",
    "How to use Xdebug for profiling?",

    "How to write unit tests in PHP?",
    "What is PHPUnit?",
    "How to install and use PHPUnit?",
    "What are test doubles?",
    "How to use mocks and stubs?",
    "What is TDD?",
    "How to apply TDD in PHP?",
    "What are integration tests?",
    "How to test database?",
    "What are functional tests?",
  ];

  static const List<String> senior = [
    "What is Clean Architecture in PHP?",
    "How to implement layered architecture?",
    "What is Domain-Driven Design?",
    "How to apply DDD in PHP?",
    "What is Event-Driven Architecture?",
    "How to implement event-driven architecture?",
    "What is CQRS?",
    "How to implement CQRS in PHP?",
    "What is Event Sourcing?",
    "How to use Event Sourcing?",
    "What is microservice architecture?",
    "How to break a monolith into microservices?",
    "What are design patterns?",
    "How to implement Singleton?",
    "How to implement Factory?",
    "What is Abstract Factory?",
    "How to implement Builder?",
    "What is the Repository pattern?",
    "How to implement Repository?",
    "What is Service Layer?",
    "How to implement Service Layer?",
    "What is Dependency Injection?",
    "How to implement DI container?",
    "What is Inversion of Control?",
    "How to apply SOLID principles?",

    "What is Laravel?",
    "How does Laravel Service Container work?",
    "What are Service Providers?",
    "How does Eloquent ORM work?",
    "What is Laravel Middleware?",
    "How does Laravel Routing work?",
    "What is Laravel Blade?",
    "How does Laravel Events work?",
    "What is Laravel Queues?",
    "How to use queues in Laravel?",
    "What is Laravel Horizon?",
    "How does Laravel Sanctum work?",
    "What is Symfony?",
    "How does Symfony Dependency Injection work?",
    "What are Symfony Bundles?",
    "How does Symfony Events work?",
    "What is Yii framework?",
    "How does CodeIgniter work?",
    "What is Phalcon?",
    "How to choose the right framework?",

    "How to optimize PHP application performance?",
    "What is horizontal scaling?",
    "How to set up load balancing?",
    "What is application-level caching?",
    "How to use Varnish?",
    "What is CDN and how to integrate it?",
    "How to optimize database?",
    "What are indexes and how to use them?",
    "How to work with big data?",
    "What is pagination and how to implement it?",
    "How to handle background tasks?",
    "What are message brokers?",
    "How to use RabbitMQ?",
    "How to use Apache Kafka?",
    "What is asynchronous programming?",

    "How to implement multi-factor authentication?",
    "What are OAuth 2.0 and OpenID Connect?",
    "How to implement SSO (Single Sign-On)?",
    "What are API security best practices?",
    "How to protect REST API?",
    "What is rate limiting and how to implement it?",
    "How to monitor application security?",
    "What are security headers?",
    "How to configure Content Security Policy?",
    "What is WAF and how to use it?",
    "How to conduct security audits?",
    "What is penetration testing?",
    "How to implement security logging?",
    "What are SIEM systems?",
    "How to comply with compliance standards?",

    "How to set up CI/CD for PHP applications?",
    "What is Docker for PHP?",
    "How to create a Dockerfile for a PHP application?",
    "What is Docker Compose?",
    "How to use Kubernetes with PHP?",
    "What is infrastructure as code?",
    "How to use Terraform for PHP applications?",
    "What is application monitoring?",
    "How to use Prometheus and Grafana?",
    "What are APM systems?",
    "How to use New Relic or DataDog?",
    "What is logging in distributed systems?",
    "How to use ELK stack?",
    "What is blue-green deployment?",
    "How to implement canary releases?",

    "How to conduct code review in PHP projects?",
    "What is technical debt and how to manage it?",
    "How to estimate task complexity?",
    "How to mentor junior developers?",
    "What are agile methodologies in PHP development?",
    "How to organize team work?",
    "What are DORA metrics?",
    "How to measure team effectiveness?",
    "How to conduct technical interviews?",
    "What is engineering culture?",
  ];
}