class PythonQuestionsEn {
  static const List<String> junior = [
    "What is Python and what are its main features?",
    "How to declare a variable in Python?",
    "What are the main data types in Python?",
    "What is dynamic typing?",
    "How do integers (int) work in Python?",
    "What are floating-point numbers (float)?",
    "How do strings (str) work in Python?",
    "What are boolean values (bool)?",
    "How does None work in Python?",
    "What are lists and how to work with them?",
    "How to use tuples?",
    "What are sets?",
    "How do dictionaries (dict) work?",
    "What's the difference between list and tuple?",
    "How to convert data types?",
    "What are f-strings?",
    "How do conditional operators (if-elif-else) work?",
    "What loops are there in Python (for, while)?",
    "How to use range()?",
    "What are list/dict/set comprehensions?",
    "How do functions work in Python?",
    "What are *args and **kwargs?",
    "How to use lambda functions?",
    "What is scope?",
    "How do global and nonlocal work?",
    "What is the ternary operator?",
    "How to use enumerate()?",
    "What does zip() do?",
    "How does sorted() work?",
    "What is slice notation?",

    "What are classes and objects?",
    "How to create a class in Python?",
    "What is 'self' in class methods?",
    "How does inheritance work?",
    "What is multiple inheritance?",
    "How to use super()?",
    "What are magic methods (__init__, __str__)?",
    "How do properties (@property) work?",
    "What are static methods (@staticmethod)?",
    "How to use class methods (@classmethod)?",
    "What are abstract classes?",
    "How do interfaces work in Python?",
    "What is encapsulation?",
    "How to implement private attributes?",
    "What is polymorphism?",
    "How does the __call__ method work?",
    "What are descriptors?",
    "How to use @dataclass?",
    "What are slots?",
    "How to implement singleton?",

    "How to read files in Python?",
    "How to write to files?",
    "What are context managers (with)?",
    "How to work with JSON?",
    "What is pickle?",
    "How to use the csv module?",
    "What does collections.defaultdict do?",
    "How does collections.Counter work?",
    "What are namedtuples?",
    "How to use datetime?",
    "What does itertools do?",
    "How to work with regular expressions?",
    "What is serialization?",
    "How to use base64?",
    "What does struct pack/unpack do?",
    "How to work with zip files?",
    "What is logging?",
    "How to use configparser?",
    "What does pathlib do?",
    "How to work with environ?",

    "How to use the math module?",
    "What does random do?",
    "How to work with the os module?",
    "What is the sys module?",
    "How to use requests?",
    "What does urllib do?",
    "How to work with subprocess?",
    "What is threading?",
    "How to use multiprocessing?",
    "What does functools do?",
    "How to work with argparse?",
    "What is the logging module?",
    "How to use unittest?",
    "What does pytest do?",
    "How to work with virtualenv?",

    "How to handle exceptions?",
    "What is try-except-finally?",
    "How to create a custom exception?",
    "What is AssertionError?",
    "How to use assert?",
    "What are doctests?",
    "How to write unit tests?",
    "What are mock objects?",
    "How to test exceptions?",
    "What are fixtures in pytest?",
    "How to measure code coverage?",
    "What is TDD?",
    "How to debug code?",
    "What does pdb do?",
    "How to use breakpoint()?",
  ];

  static const List<String> middle = [
    "What is GIL and how does it work?",
    "How does memory management work in Python?",
    "What is reference counting?",
    "How does the garbage collector work?",
    "What are weakrefs?",
    "How do decorators work?",
    "How to create your own decorator?",
    "What are decorators with parameters?",
    "How do generators work?",
    "What is yield?",
    "How to use yield from?",
    "What are coroutines?",
    "How do async/await work?",
    "What is asyncio?",
    "How to use contextlib?",
    "What are ABC (Abstract Base Classes)?",
    "How do metaclasses work?",
    "What are type hints?",
    "How to use the typing module?",
    "What are Protocols?",
    "How does @functools.cache work?",
    "What is LRU cache?",
    "How to use @dataclass?",
    "What are slots?",
    "How does __slots__ work?",

    "What is MRO?",
    "How does C3 linearization work?",
    "What are mixins?",
    "How to implement the Strategy pattern?",
    "What is the Factory Method?",
    "How to implement Abstract Factory?",
    "What is the Observer pattern?",
    "How to implement Adapter?",
    "What is the Decorator pattern?",
    "How to implement Singleton?",
    "What is the State pattern?",
    "How does the Command pattern work?",
    "What is Facade?",
    "How to implement Proxy?",
    "What is the Iterator pattern?",
    "How does the Proxy pattern work?",
    "What is Dependency Injection?",
    "How to implement Inversion of Control?",
    "What are SOLID principles?",
    "How to apply DRY?",

    "How does HTTP work in Python?",
    "What is WSGI?",
    "How to use Flask?",
    "What does Django do?",
    "How to work with FastAPI?",
    "What is ASGI?",
    "How to use aiohttp?",
    "What does requests do?",
    "How to work with WebSockets?",
    "What is REST API?",
    "How to implement GraphQL API?",
    "What does ORM do?",
    "How to use SQLAlchemy?",
    "What is Django ORM?",
    "How to work with Alembic?",
    "What does Pydantic do?",
    "How to use Marshmallow?",
    "What is middleware?",
    "How to implement authentication?",
    "What does JWT do?",

    "How to work with SQLite?",
    "What does psycopg2 do?",
    "How to use asyncpg?",
    "What is Redis?",
    "How to work with MongoDB?",
    "What does PyMongo do?",
    "How to use Motor?",
    "What is Elasticsearch?",
    "How to work with Cassandra?",
    "What does SQLAlchemy Core do?",
    "How to use ORM?",
    "What are migrations?",
    "How to work with Alembic?",
    "What does Django Migrations do?",
    "How to optimize queries?",

    "How to write integration tests?",
    "What are pytest fixtures?",
    "How to use pytest parametrize?",
    "What does unittest.mock do?",
    "How to test async code?",
    "What is hypothesis?",
    "How to measure performance?",
    "What does pytest-benchmark do?",
    "How to test APIs?",
    "What is contract testing?",
    "How to use tox?",
    "What does pre-commit do?",
    "How to set up CI/CD?",
    "What are GitHub Actions?",
    "How to use Docker?",
    "What does docker-compose do?",
    "How to work with Kubernetes?",
    "What is Helm?",
    "How to implement blue-green deployment?",
    "What are canary releases?",
  ];

  static const List<String> senior = [
    "How to design microservice architecture?",
    "What is event-driven architecture?",
    "How to implement CQRS?",
    "What is DDD?",
    "How to organize layered architecture?",
    "What is clean architecture?",
    "How to implement hexagonal architecture?",
    "What are ports and adapters?",
    "How to design for scalability?",
    "What is the Saga pattern?",
    "How to implement Event Sourcing?",
    "What is the Outbox Pattern?",
    "How to work with eventual consistency?",
    "What is a Circuit Breaker?",
    "How to implement the Retry Pattern?",
    "What is the Bulkhead Pattern?",
    "How to design for fault tolerance?",
    "What is Backpressure?",
    "How to implement compensating transactions?",
    "What is the Strangler Pattern?",
    "How to migrate from monolith to microservices?",
    "What are feature flags?",
    "How to organize A/B testing?",
    "What are canary deployments?",
    "How to design multi-tenant systems?",

    "How to profile Python code?",
    "What does cProfile do?",
    "How to use line_profiler?",
    "What is memory_profiler?",
    "How to find memory leaks?",
    "What does tracemalloc do?",
    "How to optimize CPU-bound tasks?",
    "What is multiprocessing?",
    "How to use threading?",
    "What is asyncio?",
    "How to work with GIL?",
    "What does Cython do?",
    "How to use Numba?",
    "What is JIT compilation?",
    "How to speed up code with C extensions?",
    "What does PyPy do?",
    "How to optimize database queries?",
    "What is connection pooling?",
    "How to cache data?",
    "What does Redis do as a cache?",

    // Security (20 questions)
    "How to protect against SQL injections?",
    "What does ORM do for protection?",
    "How to prevent XSS?",
    "What is CSRF protection?",
    "How to implement CORS?",
    "What does JWT do?",
    "How to work with OAuth2?",
    "What is OpenID Connect?",
    "How to store passwords?",
    "What does bcrypt do?",
    "How to implement 2FA?",
    "What is rate limiting?",
    "How to protect APIs?",
    "What does WAF do?",
    "How to work with TLS?",
    "What is mTLS?",
    "How to implement secret management?",
    "What does Vault do?",
    "How to organize security audits?",
    "What is penetration testing?",

    "How to conduct code reviews?",
    "What is pair programming?",
    "How to organize knowledge sharing?",
    "What are tech talks?",
    "How to mentor junior developers?",
    "What is a mentorship program?",
    "How to conduct technical interviews?",
    "What is an engineering ladder?",
    "How to measure team performance?",
    "What are DORA metrics?",
    "How to manage technical debt?",
    "What is tech debt assessment?",
    "How to organize CI/CD pipeline?",
    "What is trunk-based development?",
    "How to implement feature flags management?",
    "What are canary releases?",
    "How to organize incident management?",
    "What is postmortem analysis?",
    "How to conduct retrospectives?",
    "What are agile methodologies?",

    "What are the new features in Python?",
    "What is pattern matching?",
    "How does structural pattern matching work?",
    "What's new in asyncio?",
    "How to use the type system?",
    "What are Protocols?",
    "How does TypedDict work?",
    "What's new in Python 3.11?",
    "How to use performance improvements?",
    "What is JIT in Python?",
    "How does PyScript work?",
    "What is WebAssembly in Python?",
    "How to use Python for ML?",
    "What does PyTorch do?",
    "How to work with TensorFlow?",
  ];
}