class RustQuestionsEn {
  static const List<String> junior = [
    "What is Rust and what are its main features?",
    "What's the difference between Rust and other system languages?",
    "How to install Rust and Cargo?",
    "What is Cargo and what is it used for?",
    "How to create a new project with Cargo?",
    "How to compile and run a Rust program?",
    "What are Cargo.toml and Cargo.lock?",
    "What is the basic syntax of Rust?",
    "How to declare a variable in Rust?",
    "What are let, mut, and const?",
    "What's the difference between let and let mut?",
    "What scalar data types are there in Rust?",
    "What are integer types (i8, i16, i32, i64, i128, isize)?",
    "What are unsigned integer types (u8, u16, u32, u64, u128, usize)?",
    "How do floating-point numbers (f32, f64) work?",
    "What is the bool type?",
    "How does the char type work?",
    "What are tuples in Rust?",
    "How to declare and use a tuple?",
    "What are arrays in Rust?",
    "How to declare an array?",
    "What's the difference between an array and a slice?",
    "What are str and String?",
    "What's the difference between &str and String?",
    "How to create a string?",
    "How to work with strings?",
    "What is the unit type ()?",
    "What operators are there in Rust?",
    "How do arithmetic operators work?",
    "How do comparison operators work?",

    "How to declare a function in Rust?",
    "How to specify parameter types?",
    "How to specify return type?",
    "What is the return operator?",
    "How does implicit return work?",
    "How do if-else conditional operators work?",
    "Can if be used in expressions?",
    "How does the loop work?",
    "How to use break and continue in a loop?",
    "How does the while loop work?",
    "How does the for loop work?",
    "How to iterate over ranges with for?",
    "How to iterate over collections with for?",
    "What is the match expression?",
    "How to use match for pattern matching?",
    "What is exhaustive matching?",
    "How to use _ in match?",
    "What is if let?",
    "When to use if let instead of match?",
    "What is while let?",
    "How to use the ? operator for error handling?",
    "What are macros in Rust?",
    "How to use println! and format!?",
    "What is the vec! macro?",
    "How to create a custom macro?",

    "What is the ownership system in Rust?",
    "What are the ownership rules?",
    "What is move in Rust?",
    "What's the difference between copy and move?",
    "Which types implement the Copy trait?",
    "What is borrowing in Rust?",
    "What are references (&) in Rust?",
    "What's the difference between & and &mut?",
    "What are the borrowing rules?",
    "What are lifetimes in Rust?",
    "How to annotate lifetimes?",
    "What are lifetime elision rules?",
    "How do lifetimes work in functions?",
    "What is the 'static lifetime?",
    "How does ownership work in structs?",
    "How does ownership work in enums?",
    "What are slices and how do they work with ownership?",
    "How to use string slices?",
    "How to use array slices?",
    "What is Deref coercion?",

    "What are structs in Rust?",
    "How to declare a struct?",
    "How to create a struct instance?",
    "What is field init shorthand?",
    "How to use struct update syntax?",
    "What are tuple structs?",
    "What are unit-like structs?",
    "How to implement methods for structs?",
    "What is an impl block?",
    "What's the difference between methods and associated functions?",
    "What are enums in Rust?",
    "How to declare an enum?",
    "How to use enums with data?",
    "What is Option<T> and how to use it?",
    "What is Result<T, E> and how to use it?",

    "What is Vec<T> and how to use it?",
    "How to add an element to a vector?",
    "How to remove an element from a vector?",
    "What is HashMap<K, V>?",
    "How to add a key-value pair to a HashMap?",
    "How to get a value from a HashMap?",
    "What is String and how to work with it?",
    "How to convert &str to String?",
    "How to convert String to &str?",
    "What is VecDeque and when to use it?",
  ];

  static const List<String> middle = [
    "What are traits in Rust?",
    "How to declare a trait?",
    "How to implement a trait for a type?",
    "What are trait bounds?",
    "How to use traits as parameters?",
    "What is impl Trait in return position?",
    "What are trait objects?",
    "How to use dyn Trait?",
    "What's the difference between impl Trait and dyn Trait?",
    "What are associated types in traits?",
    "How to use associated types?",
    "What are generic types in Rust?",
    "How to declare a generic function?",
    "How to declare a generic struct?",
    "How to declare a generic enum?",
    "How to use generics with trait bounds?",
    "What is a where clause?",
    "When to use where instead of angle bracket syntax?",
    "What are blanket implementations?",
    "How to implement a trait for all types satisfying a condition?",
    "What are the From and Into traits?",
    "How to use From and Into for conversions?",
    "What is the Drop trait?",
    "How to implement the Drop trait?",
    "What are the Clone and Copy traits?",

    "What is the newtype pattern?",
    "How to use newtype for type safety?",
    "What are type aliases?",
    "How to create a type alias?",
    "What is the Never type (!)?",
    "When is the Never type used?",
    "What are smart pointers in Rust?",
    "What is Box<T> and when to use it?",
    "What is Rc<T> and when to use it?",
    "What is Arc<T> and when to use it?",
    "What's the difference between Rc and Arc?",
    "What is RefCell<T> and when to use it?",
    "What is Cell<T> and when to use it?",
    "What's the difference between RefCell and Cell?",
    "What is interior mutability?",
    "How does interior mutability work in Rust?",
    "What is Cow (Copy on Write)?",
    "When to use Cow?",
    "What is the Builder pattern?",
    "How to implement the Builder pattern in Rust?",

    "What error handling methods are there in Rust?",
    "What's the difference between panic! and Result?",
    "When to use panic! and when to use Result?",
    "How to use unwrap and expect?",
    "When can unwrap be used?",
    "How to use the ? operator for error propagation?",
    "How to create a custom error type?",
    "What is the Error trait?",
    "How to implement the Error trait for your type?",
    "What is the thiserror library?",
    "How to use thiserror to create errors?",
    "What is the anyhow library?",
    "How to use anyhow to simplify error handling?",
    "How to convert between different error types?",
    "What is Box<dyn Error>?",

    "What are threads in Rust?",
    "How to create a new thread?",
    "How to wait for a thread to finish?",
    "What are Move closures?",
    "How to use move with closures?",
    "What are channels in Rust?",
    "How to use mpsc channels?",
    "What is Mutex<T> and when to use it?",
    "How to use Mutex for synchronization?",
    "What is RwLock<T> and when to use it?",
    "What's the difference between Mutex and RwLock?",
    "What are atomic types?",
    "How to use AtomicUsize and other atomic types?",
    "What are async/await in Rust?",
    "How to declare an async function?",
    "What is the Future trait?",
    "How to execute an async function?",
    "What is runtime in async Rust?",
    "What are tokio and async-std?",
    "How to choose between tokio and async-std?",

    "What is the module system in Rust?",
    "How to declare a module?",
    "How to use pub for visibility control?",
    "What are use declarations?",
    "How to re-export items with pub use?",
    "What is the file structure of modules?",
    "How to organize code across multiple files?",
    "What are crate and module?",
    "What's the difference between crate and mod?",
    "How to use external crates?",

    "How to write unit tests in Rust?",
    "How to use #[cfg(test)]?",
    "How to run tests?",
    "How to write integration tests?",
    "What are doc tests?",
    "How to write documentation with examples?",
    "How to use assert! and assert_eq!?",
    "How to test private functions?",
    "What is property-based testing?",
    "How to use proptest for property-based testing?",
  ];

  static const List<String> senior = [
    "What are higher-ranked trait bounds (HRTB)?",
    "How to use the for<'a> syntax?",
    "What are associated type constructors?",
    "How to use generic associated types (GAT)?",
    "What are const generics?",
    "How to use const parameters in generics?",
    "What are trait objects with multiple traits?",
    "How to use dyn Trait1 + Trait2?",
    "What are unsized types?",
    "How to work with types whose size is unknown at compile time?",
    "What are coercions in Rust?",
    "What types of coercions exist?",
    "What is variance in Rust's type system?",
    "How do covariance, contravariance, and invariance work?",
    "What is phantom data?",
    "How to use PhantomData<T>?",
    "What is unsafe Rust?",
    "When can unsafe code be used?",
    "What capabilities does unsafe Rust provide?",
    "What are unsafe traits and unsafe functions?",

    "What types of macros exist in Rust?",
    "What's the difference between declarative and procedural macros?",
    "How to create a declarative macro with macro_rules!?",
    "What are procedural macros?",
    "How to create a derive macro?",
    "How to create an attribute-like macro?",
    "How to create a function-like macro?",
    "What are the quote and syn libraries?",
    "How to use quote for code generation?",
    "What are compile-time computations?",
    "How to use const functions?",
    "What are const generics?",
    "How to use build scripts?",
    "What is conditional compilation with #[cfg]?",
    "How to use features in Cargo?",

    "How to analyze Rust code performance?",
    "What is benchmarking in Rust?",
    "How to use criterion for benchmarks?",
    "What is profiling Rust applications?",
    "How to use perf and flamegraph?",
    "What are zero-cost abstractions in Rust?",
    "How does Rust ensure zero-cost abstractions?",
    "What is inline assembly in Rust?",
    "How to use the asm! macro?",
    "What is SIMD in Rust?",
    "How to use SIMD instructions?",
    "What is no_std programming?",
    "How to create a no_std application?",
    "What is embedded Rust?",
    "How to use Rust for embedded development?",

    "What is formal verification in Rust?",
    "How to use Rust for safety-critical systems?",
    "What is the RustBelt project?",
    "How does Rust's type system work from a formal verification perspective?",
    "What is fuzz testing in Rust?",
    "How to use cargo fuzz?",
    "What is property-based testing with proptest?",
    "How to use model checking in Rust?",
    "What is concurrency safety in Rust?",
    "How does Rust prevent data races?",
    "What are memory safety guarantees?",
    "How does the borrow checker work from a safety perspective?",
    "What is unsafe code and its risks?",
    "How to safely use unsafe code?",
    "What is the Rust security advisory database?",

    "How to work with raw pointers in Rust?",
    "What's the difference between *const T and *mut T?",
    "How to work with FFI (Foreign Function Interface)?",
    "How to call C code from Rust?",
    "How to call Rust code from C?",
    "What is #[repr(C)]?",
    "How to work with system calls?",
    "What is the libc crate?",
    "How to create a system daemon in Rust?",
    "What is signal handling in Rust?",
    "How to work with the filesystem at a low level?",
    "What is mmap in Rust?",
    "How to work with network sockets?",
    "What is io_uring in Rust?",
    "How to create a high-performance network server?",

    "How to design large Rust applications?",
    "What are module hierarchy best practices?",
    "How to organize a workspace in Cargo?",
    "What is the edition system in Rust?",
    "What's the difference between Rust 2015, 2018, and 2021?",
    "How to migrate between editions?",
    "What is Rust language server (RLS)?",
    "How to use rust-analyzer?",
    "What is cargo clippy and how to use it?",
    "What are best practices for Rust development?",
  ];
}