class SQLQuestionsEn {
  static const List<String> junior = [
    "What is SQL and what is it used for?",
    "What are the main types of databases?",
    "What's the difference between SQL and NoSQL?",
    "What is a relational database?",
    "What are the main operations in SQL?",
    "What is a table in a database?",
    "What is a column in a table?",
    "What is a row (record) in a table?",
    "What is a PRIMARY KEY?",
    "What is a FOREIGN KEY?",
    "How to create a database?",
    "How to create a table?",
    "What data types exist in SQL?",
    "What's the difference between CHAR and VARCHAR?",
    "What are INTEGER, DECIMAL, FLOAT?",
    "How to use DATE and TIMESTAMP?",
    "What is the BOOLEAN type?",
    "How to insert data into a table?",
    "How to update data in a table?",
    "How to delete data from a table?",
    "How to select all data from a table?",
    "How to select specific columns?",
    "How to filter data with WHERE?",
    "How to sort data with ORDER BY?",
    "How to limit the number of returned rows?",
    "What is NULL and how to work with it?",
    "How to check for NULL values?",
    "How to use aliases for columns?",
    "How to use aliases for tables?",
    "What are comments in SQL?",

    "How to use the = operator?",
    "How to use the >, <, >=, <= operators?",
    "How to use the <> or != operator?",
    "How to use the BETWEEN operator?",
    "How to use the IN operator?",
    "How to use the LIKE operator?",
    "What are wildcards in LIKE?",
    "How to use % in LIKE?",
    "How to use _ in LIKE?",
    "How to use the NOT operator?",
    "How to combine conditions with AND?",
    "How to combine conditions with OR?",
    "What's the difference between AND and OR?",
    "How to use parentheses for grouping conditions?",
    "How to use the IS NULL operator?",
    "How to use the IS NOT NULL operator?",
    "How to filter dates?",
    "How to filter strings?",
    "How to use CASE in WHERE?",
    "How to use subqueries in WHERE?",

    "What are aggregate functions?",
    "How to use COUNT()?",
    "How to use SUM()?",
    "How to use AVG()?",
    "How to use MIN()?",
    "How to use MAX()?",
    "What's the difference between COUNT(*) and COUNT(column)?",
    "How to use GROUP BY?",
    "What is GROUP BY for?",
    "How to use HAVING?",
    "What's the difference between WHERE and HAVING?",
    "How to use string functions?",
    "What is CONCAT()?",
    "How to use UPPER() and LOWER()?",
    "How to use SUBSTRING()?",
    "How to use LENGTH()?",
    "How to use TRIM()?",
    "How to use REPLACE()?",
    "How to use mathematical functions?",
    "What is ROUND()?",
    "How to use ABS()?",
    "How to use CEIL() and FLOOR()?",
    "How to use date and time functions?",
    "What is NOW()?",
    "How to use DATE_FORMAT()?",

    "What are JOINs in SQL?",
    "What are JOIN operations for?",
    "What is INNER JOIN?",
    "How does INNER JOIN work?",
    "What is LEFT JOIN?",
    "How does LEFT JOIN work?",
    "What is RIGHT JOIN?",
    "How does RIGHT JOIN work?",
    "What is FULL OUTER JOIN?",
    "What's the difference between different JOIN types?",
    "How to use multiple JOINs in one query?",
    "What is self JOIN?",
    "When to use self JOIN?",
    "What is CROSS JOIN?",
    "When to use CROSS JOIN?",

    "How to insert a single row?",
    "How to insert multiple rows?",
    "How to update a single row?",
    "How to update multiple rows?",
    "How to delete a single row?",
    "How to delete multiple rows?",
    "How to use LIMIT when updating?",
    "How to use LIMIT when deleting?",
    "What is TRUNCATE TABLE?",
    "What's the difference between DELETE and TRUNCATE?",
  ];

  static const List<String> middle = [
    "What are subqueries?",
    "How to use a subquery in WHERE?",
    "How to use a subquery in SELECT?",
    "How to use a subquery in FROM?",
    "What are correlated subqueries?",
    "What's the difference between correlated and non-correlated subqueries?",
    "What is EXISTS?",
    "How to use EXISTS with subqueries?",
    "What is NOT EXISTS?",
    "What are Common Table Expressions (CTE)?",
    "How to use WITH for CTE?",
    "How to use recursive CTE?",
    "What are window functions?",
    "How to use ROW_NUMBER()?",
    "How to use RANK() and DENSE_RANK()?",
    "How to use LAG() and LEAD()?",
    "How to use SUM() as a window function?",
    "What is PARTITION BY in window functions?",
    "What is ORDER BY in window functions?",
    "How to use window functions with frames?",

    "What are indexes in SQL?",
    "Why are indexes needed?",
    "How to create an index?",
    "How to delete an index?",
    "What types of indexes exist?",
    "What is a B-tree index?",
    "What is a composite index?",
    "How do composite indexes work?",
    "What is a unique index?",
    "How to create a unique index?",
    "What is a covering index?",
    "How to use EXPLAIN?",
    "How to analyze query execution plan?",
    "What is full-text search?",
    "How to create a full-text index?",

    "What are transactions in SQL?",
    "Why are transactions needed?",
    "How to start a transaction?",
    "How to commit a transaction?",
    "How to rollback a transaction?",
    "What is ACID?",
    "What does Atomicity mean?",
    "What does Consistency mean?",
    "What does Isolation mean?",
    "What does Durability mean?",
    "What are isolation levels?",
    "What isolation levels exist?",
    "What is READ UNCOMMITTED?",
    "What is READ COMMITTED?",
    "What is REPEATABLE READ?",

    "What are constraints?",
    "How to add a PRIMARY KEY?",
    "How to add a FOREIGN KEY?",
    "How to add a UNIQUE constraint?",
    "How to add a CHECK constraint?",
    "How to add a NOT NULL constraint?",
    "How to delete a constraint?",
    "What is cascade delete?",
    "How to configure ON DELETE CASCADE?",
    "What is ON UPDATE CASCADE?",
    "How does RESTRICT work on delete?",
    "How does SET NULL work on delete?",
    "What is referential integrity?",
    "How to check data integrity?",
    "What are triggers?",

    "How to optimize slow queries?",
    "What is query optimization?",
    "How to use indexes for optimization?",
    "What is query statistics?",
    "How to analyze query performance?",
    "What are temporary tables?",
    "How to use temporary tables?",
    "What are materialized views?",
    "How to use materialized views?",
    "What is query caching?",
    "How does query caching work?",
    "What is connection pooling?",
    "How to configure connection pool?",
    "What is a deadlock?",
    "How to avoid deadlock?",

    "What's the difference between MySQL and PostgreSQL?",
    "What's the difference between SQLite and other DBMS?",
    "How to work with dates in different DBMS?",
    "What are the specifics of string functions in different DBMS?",
    "How do constraints work in different DBMS?",
    "What are stored procedures?",
    "How to create a stored procedure?",
    "What are functions in SQL?",
    "How to create a custom function?",
    "How to work with JSON in SQL?",
  ];

  static const List<String> senior = [
    "What is database normalization?",
    "What normal forms exist?",
    "What is first normal form (1NF)?",
    "What is second normal form (2NF)?",
    "What is third normal form (3NF)?",
    "What is Boyce-Codd normal form (BCNF)?",
    "When to denormalize a database?",
    "What is denormalization?",
    "How to design a database schema?",
    "What are ER diagrams?",
    "How to create an ER diagram?",
    "What are conceptual, logical, and physical models?",
    "How to choose appropriate data types?",
    "How to design for scalability?",
    "What is sharding?",
    "How to implement sharding?",
    "What is replication?",
    "What types of replication exist?",
    "What is master-slave replication?",
    "What is master-master replication?",
    "How to set up replication?",
    "What is database clustering?",
    "How to set up a cluster?",
    "What is high availability?",
    "How to ensure database high availability?",

    "How to conduct database performance monitoring?",
    "What metrics to monitor?",
    "What is slow query log?",
    "How to analyze slow queries?",
    "How to use query profiling?",
    "What is query execution plan?",
    "How to read execution plan?",
    "What is cost-based optimizer?",
    "How does query optimizer work?",
    "What are index scans?",
    "What are full table scans?",
    "How to avoid full table scans?",
    "What is partition pruning?",
    "How to use partitioning?",
    "What types of partitioning exist?",
    "What is horizontal partitioning?",
    "What is vertical partitioning?",
    "How to set up partitioning?",
    "What are materialized views?",
    "How to use materialized views for performance?",

    "How to manage users in SQL?",
    "How to create a user?",
    "How to delete a user?",
    "What are roles in SQL?",
    "How to create a role?",
    "How to assign permissions to a role?",
    "What types of privileges exist?",
    "How to grant permissions on a table?",
    "How to revoke permissions?",
    "What are GRANT and REVOKE?",
    "How to set up row-level security?",
    "What is row-level security?",
    "How to set up column-level security?",
    "What is SQL injection?",
    "How to protect against SQL injection?",

    "What backup strategies exist?",
    "What is full backup?",
    "What is incremental backup?",
    "What is differential backup?",
    "How to backup a database?",
    "How to restore a database from backup?",
    "What is point-in-time recovery?",
    "How to set up PITR?",
    "What is WAL (Write-Ahead Logging)?",
    "How does WAL work?",
    "What is binlog in MySQL?",
    "How to use binlog for replication?",
    "What are transaction logs?",
    "How to configure transaction logging?",
    "What is disaster recovery?",

    "What is a Data Warehouse?",
    "What's the difference between OLTP and OLAP?",
    "What is ETL?",
    "How to design an ETL process?",
    "What is a star schema?",
    "What is a snowflake schema?",
    "How to use SQL for analytics?",
    "What are window functions for analytics?",
    "How to use ROLLUP and CUBE?",
    "What are GROUPING SETS?",

    "How to manage database migrations?",
    "What are database migrations?",
    "How to create a migration system?",
    "How to rollback a migration?",
    "What is version control for databases?",
    "How to integrate migrations with CI/CD?",
    "How to test migrations?",
    "What is blue-green deployment for databases?",
    "How to implement zero-downtime migrations?",
    "What is database refactoring?",
  ];
}