class SwiftQuestionsEn {
  static const List<String> junior = [
    "What is Swift and how does it differ from Objective-C?",
    "What are the main data types in Swift?",
    "How to declare a variable (var) and constant (let)?",
    "What are optional types in Swift?",
    "How does the safe unwrapping operator (if let) work?",
    "What is guard let and how does it differ from if let?",
    "How does the nil-coalescing operator (??) work?",
    "What string interpolations are available in Swift?",
    "How do conditional expressions if and switch work?",
    "What loops are there in Swift (for, while, repeat-while)?",
    "How do ranges work in Swift?",
    "What are tuples in Swift?",
    "How to declare and use an array?",
    "How to work with dictionaries?",
    "What is a set and when to use it?",
    "How do closures work in Swift?",
    "What are autoclosures?",
    "How to use higher-order functions (map, filter, reduce)?",
    "What are enums in Swift?",
    "How do associated values in enums work?",
    "What are raw values in enums?",
    "How to use the defer operator?",
    "What is the do-try-catch operator?",
    "How to create and throw errors?",
    "What is typealias?",
    "How do computed properties work?",
    "What are property observers (willSet, didSet)?",
    "How to use lazy properties?",
    "What are subscripts?",
    "How to work with Any and AnyObject types?",

    "How to declare a class and a struct?",
    "What's the difference between class and struct?",
    "What are value types and reference types?",
    "How does initialization (init) work in Swift?",
    "What are designated and convenience initializers?",
    "How does inheritance work in Swift?",
    "What is method overriding (override)?",
    "How to use the final keyword?",
    "What are protocols in Swift?",
    "How to use extensions for protocols?",
    "What is protocol composition?",
    "How does delegation work?",
    "What are generics in Swift?",
    "How to use where with generics?",
    "What is associatedtype in protocols?",
    "How do operators (operator overloading) work?",
    "What are custom operators?",
    "How to use access control (open, public, internal, fileprivate, private)?",
    "What is memory management in Swift?",
    "How does ARC (Automatic Reference Counting) work?",
    "What are weak and unowned references?",
    "How to avoid retain cycles?",
    "What is deinit?",
    "How to use KeyPath?",
    "What are property wrappers?",

    "What is the ViewController lifecycle?",
    "How to create UI programmatically (without storyboard)?",
    "How to work with UITableView?",
    "What are UITableViewDataSource and UITableViewDelegate?",
    "How to use UICollectionView?",
    "How to set up Auto Layout programmatically?",
    "What are Stack Views?",
    "How to work with UIScrollView?",
    "What is the responder chain?",
    "How to handle gestures (UIGestureRecognizer)?",
    "How to work with animations (UIView.animate)?",
    "What is Core Animation?",
    "How to use UIAlertController?",
    "What is UINavigationController?",
    "How to pass data between ViewControllers?",
    "What is segue and how to use it?",
    "How to work with UITabBarController?",
    "What is the MVC pattern in iOS?",
    "How to use UserDefaults?",
    "What is FileManager?",
    "How to work with networking (URLSession)?",
    "What is Codable?",
    "How to parse JSON?",
    "What is DispatchQueue?",
    "How to execute asynchronous tasks?",

    "What is SwiftUI and how does it differ from UIKit?",
    "How does View work in SwiftUI?",
    "What are State and Binding?",
    "How to use ObservableObject?",
    "What is @Published?",
    "How to work with List in SwiftUI?",
    "What are VStack, HStack, ZStack?",
    "How to use modifiers in SwiftUI?",
    "What is @Environment?",
    "How to navigate in SwiftUI?",

    "How to write unit tests in XCTest?",
    "What is XCTestCase?",
    "How to use XCTAssert?",
    "What are test doubles (mock, stub, fake)?",
    "How to test asynchronous code?",
    "How to debug Swift code?",
    "What are LLDB commands?",
    "How to use breakpoints?",
    "What are Instruments?",
    "How to measure application performance?",
  ];

  static const List<String> middle = [
    "How does copy-on-write work for value types?",
    "What are indirect enums?",
    "How to use recursive constraints in generics?",
    "What are opaque return types (some)?",
    "How does @dynamicMemberLookup work?",
    "What are property wrappers and how to create custom ones?",
    "How to use @resultBuilder?",
    "What is memory layout of types?",
    "How to work with pointers (UnsafePointer)?",
    "What is @autoclosure and when to use it?",
    "How to implement pattern matching?",
    "What is the ~= operator?",
    "How to use where in protocols?",
    "What is conditional conformance?",
    "How does @objc dynamic work?",
    "What is KeyPath and how to use it?",
    "How to implement custom collections?",
    "What are lazy sequences?",
    "How to use Mirror for reflection?",
    "What are @available and #available?",
    "How to work with DispatchGroup?",
    "What are Operation and OperationQueue?",
    "How to implement custom operators?",
    "What is @inlinable?",
    "How to use @main for entry point?",

    "How does multiple inheritance through protocols work?",
    "What is protocol-oriented programming?",
    "How to use protocol extensions?",
    "What are default implementations in protocols?",
    "How to implement type erasure?",
    "What are existential types?",
    "How to use associatedtype in protocols?",
    "What are self and Self in protocols?",
    "How to implement the builder pattern?",
    "What is dependency injection?",
    "How to use the factory pattern?",
    "What is the strategy pattern?",
    "How to implement the observer pattern?",
    "What is the decorator pattern?",
    "How to use the adapter pattern?",
    "What is the singleton pattern and its pros/cons?",
    "How to implement the coordinator pattern?",
    "What is the MVVM pattern?",
    "How to use VIPER architecture?",
    "What is clean architecture?",

    "How does the UIViewController lifecycle work?",
    "What is the responder chain and how does it work?",
    "How to implement custom UI components?",
    "What are layer-backed views?",
    "How to work with Core Graphics?",
    "What is Core Animation and CALayer?",
    "How to implement custom transitions?",
    "What are UIResponder and UIEvent?",
    "How to handle multi-touch?",
    "What is hit testing?",
    "How to optimize UITableView performance?",
    "What is prefetching in UICollectionView?",
    "How to implement compositional layout?",
    "What is diffable data source?",
    "How to work with UIScrollView and paging?",
    "What are UIScrollViewDelegate methods?",
    "How to implement custom UINavigationController?",
    "What are UIWindow and UIApplication?",
    "How to work with UIAppearance?",
    "What are trait collections?",

    "How does the View lifecycle work in SwiftUI?",
    "What are @StateObject and @ObservedObject?",
    "How to use @EnvironmentObject?",
    "What is @FetchRequest for Core Data?",
    "How to implement custom ViewModifier?",
    "What is PreferenceKey?",
    "How to work with GeometryReader?",
    "What is matchedGeometryEffect?",
    "How to implement animations in SwiftUI?",
    "What are transitions in SwiftUI?",
    "How to use @ViewBuilder?",
    "What is custom Binding?",
    "How to implement Redux in SwiftUI?",
    "What are @AppStorage and @SceneStorage?",
    "How to test SwiftUI views?",

    "How does DispatchQueue work?",
    "What is QoS (Quality of Service)?",
    "How to use OperationQueue?",
    "What are async/await in Swift?",
    "How does Task work?",
    "What are actors in Swift?",
    "How to use @MainActor?",
    "What is the Sendable protocol?",
    "How to avoid data races?",
    "What is thread sanitizer?",

    "How to test async code?",
    "What is XCTestExpectation?",
    "How to use Quick/Nimble?",
    "What is snapshot testing?",
    "How to test Combine publishers?",
    "What is UI testing in XCTest?",
    "How to use XCUITest?",
    "What are test plans?",
    "How to measure code coverage?",
    "What are performance tests?",
  ];

  static const List<String> senior = [
    "How to design scalable architecture for iOS applications?",
    "What is clean architecture and how to apply it?",
    "How to implement domain-driven design?",
    "What is hexagonal architecture?",
    "How to organize feature modules?",
    "What is a dependency injection framework?",
    "How to implement modular design?",
    "What is unidirectional data flow?",
    "How to use Redux architecture?",
    "What is The Composable Architecture (TCA)?",
    "How to implement MVVM-C (Coordinator)?",
    "What is VIP (View-Interactor-Presenter)?",
    "How to organize multi-layer architecture?",
    "What are SOLID principles?",
    "How to apply the dependency inversion principle?",
    "What is the interface segregation principle?",
    "How to implement event sourcing?",
    "What is the CQRS pattern?",
    "How to design for testability?",
    "What is design system architecture?",
    "How to organize a shared kernel?",
    "What are bounded contexts?",
    "How to implement feature flags?",
    "What is A/B testing architecture?",
    "How to design for accessibility?",

    "How to profile iOS applications?",
    "What are Instruments and how to use them?",
    "How to measure memory usage?",
    "How to optimize app launch time?",
    "What are pre-main and post-main times?",
    "How to reduce binary size?",
    "What is dead code stripping?",
    "How to use dynamic linking?",
    "What is app thinning?",
    "How to work with memory leaks?",
    "What is retain cycle detection?",
    "How to use memory graph debugger?",
    "How to optimize UITableView performance?",
    "What are cell reuse and prefetching?",
    "How to work with offscreen rendering?",
    "What is rasterization?",
    "How to optimize animations?",
    "What is CADisplayLink?",
    "How to measure energy impact?",
    "What is power consumption optimization?",

    "How to implement secure storage?",
    "What are Keychain Services?",
    "How to work with biometric authentication?",
    "What is the LocalAuthentication framework?",
    "How to protect data in transit?",
    "What is certificate pinning?",
    "How to implement a secure network layer?",
    "What is App Transport Security?",
    "How to protect against MITM attacks?",
    "What are OAuth 2.0 and OpenID Connect?",
    "How to implement JWT authentication?",
    "What is role-based access control?",
    "How to protect against reverse engineering?",
    "What are obfuscation techniques?",
    "How to use C code for security?",
    "What is RASP (Runtime App Self-Protection)?",
    "How to implement secure logging?",
    "What is GDPR compliance?",
    "How to work with PII data?",
    "What is the data minimization principle?",

    "How to organize a code review process?",
    "What is pair programming?",
    "How to conduct technical interviews?",
    "What is an engineering ladder?",
    "How to mentor junior developers?",
    "What is a mentorship program?",
    "How to organize knowledge sharing?",
    "What are tech talks?",
    "How to conduct architectural reviews?",
    "What are ADRs (Architecture Decision Records)?",
    "How to manage technical debt?",
    "What is tech debt assessment?",
    "How to organize a CI/CD pipeline?",
    "What is trunk-based development?",
    "How to implement feature flags management?",

    "What are the new features in Swift?",
    "What is Swift Concurrency?",
    "How does the actor model work?",
    "What are distributed actors?",
    "How to use Swift for server-side?",
    "What is the Vapor framework?",
    "How does SwiftNIO work?",
    "What's new in SwiftUI?",
    "How to use Swift Charts?",
    "What is Swift Regex?",
    "How do Swift macros work?",
    "What are embedded DSLs?",
    "How to use machine learning in iOS?",
    "What is Core ML?",
    "How to work with Create ML?",
    "What are ARKit and RealityKit?",
    "How to implement AR experiences?",
    "What are Swift Playgrounds?",
    "How to use Swift on Linux?",
    "What are trends in iOS development?",
  ];
}