class TypescriptQuestionsEn {
  static const List<String> junior = [
    "What is TypeScript and what are its advantages?",
    "What's the difference between TypeScript and JavaScript?",
    "How to install TypeScript?",
    "How to compile a TypeScript file?",
    "What is tsconfig.json?",
    "What are the main settings in tsconfig.json?",
    "What is strict typing?",
    "How to declare a variable with a type?",
    "What are the basic types in TypeScript?",
    "What is type annotation?",
    "How does the string type work?",
    "How does the number type work?",
    "How does the boolean type work?",
    "What is the any type?",
    "When to use any?",
    "What is the unknown type?",
    "What's the difference between any and unknown?",
    "What is the void type?",
    "When to use void?",
    "What is the never type?",
    "When to use never?",
    "What are null and undefined types?",
    "How do arrays work in TypeScript?",
    "How to declare an array of numbers?",
    "How to declare an array of strings?",
    "What is a tuple type?",
    "How to use tuples?",
    "What are enums?",
    "How to create an enum?",
    "What types of enums exist?",

    "How to declare a function in TypeScript?",
    "How to specify function parameter types?",
    "How to specify return type?",
    "What are optional parameters?",
    "How to make a parameter optional?",
    "What are default parameters?",
    "How to set default values?",
    "What are rest parameters?",
    "How to use ... in parameters?",
    "What is function overloading?",
    "How to declare an overloaded function?",
    "What are arrow functions in TypeScript?",
    "How to specify types for arrow functions?",
    "What is a function type?",
    "How to declare a function type?",
    "What are higher-order functions?",
    "How to pass functions as arguments?",
    "What are callback types?",
    "How to use 'this' in TypeScript?",
    "What are 'this' parameters?",
    "How to use generics in functions?",
    "What are generic functions?",
    "How to create a generic function?",
    "What is type inference in functions?",
    "When does TypeScript infer types automatically?",

    "How to type objects?",
    "What are interfaces?",
    "How to create an interface?",
    "What are optional properties?",
    "How to make a property optional?",
    "What are readonly properties?",
    "How to make a property readonly?",
    "What are index signatures?",
    "How to use index signatures?",
    "What are function types in interfaces?",
    "How to describe a function in an interface?",
    "What is 'extends' for interfaces?",
    "How to inherit interfaces?",
    "What are type aliases?",
    "What's the difference between 'type' and 'interface'?",
    "When to use 'type' vs 'interface'?",
    "What are intersection types?",
    "How to use & for types?",
    "What are union types?",
    "How to use | for types?",

    "How to declare a class in TypeScript?",
    "How to type class properties?",
    "How to type class methods?",
    "What is a class constructor?",
    "How to type constructor parameters?",
    "What are public, private, protected?",
    "What's the difference between access modifiers?",
    "What is 'readonly' in classes?",
    "How to use readonly properties?",
    "What are static properties and methods?",
    "How to declare a static class member?",
    "What are abstract classes?",
    "How to create an abstract class?",
    "What is class inheritance?",
    "How to use 'extends' for classes?",

    "How to use the 'any' type carefully?",
    "What is type assertion?",
    "How to use 'as' for type assertions?",
    "What is the non-null assertion operator?",
    "How to use the ! operator?",
    "What are const assertions?",
    "How to use 'as const'?",
    "What is the 'keyof' operator?",
    "How to use 'keyof'?",
    "What is the 'typeof' operator in TypeScript?",
  ];

  static const List<String> middle = [
    "What are conditional types?",
    "How to use conditional types?",
    "What is the 'infer' keyword?",
    "How to use 'infer' in conditional types?",
    "What are mapped types?",
    "How to create a mapped type?",
    "What is Readonly<T>?",
    "What is Partial<T>?",
    "What is Required<T>?",
    "What is Pick<T, K>?",
    "What is Omit<T, K>?",
    "What is Record<K, T>?",
    "What is Exclude<T, U>?",
    "What is Extract<T, U>?",
    "What is NonNullable<T>?",
    "What is Parameters<T>?",
    "What is ReturnType<T>?",
    "What is ConstructorParameters<T>?",
    "What is InstanceType<T>?",
    "How to create custom utility types?",

    "What are generics in TypeScript?",
    "Why are generics needed?",
    "How to declare a generic interface?",
    "How to declare a generic class?",
    "How to use generic constraints?",
    "What is 'extends' in generics?",
    "How to constrain a generic parameter?",
    "What are default type parameters?",
    "How to set default type for generics?",
    "What are generic conditional types?",
    "How to use conditional types with generics?",
    "What are generic mapped types?",
    "How to create mapped types with generics?",
    "What are 'keyof' and generics?",
    "How to use 'keyof' with generic types?",
    "What is 'typeof' with generics?",
    "How to combine generics with union types?",
    "How to combine generics with intersection types?",
    "What is variance in generics?",
    "What are covariance and contravariance?",

    "What are modules in TypeScript?",
    "How to use import/export?",
    "What is default export?",
    "What are named exports?",
    "How to re-export modules?",
    "What are namespaces?",
    "How to create a namespace?",
    "What's the difference between modules and namespaces?",
    "When to use modules vs namespaces?",
    "What are ambient declarations?",
    "How to declare an ambient module?",
    "What are declaration files?",
    "What are .d.ts files?",
    "How to create a declaration file?",
    "What are triple-slash directives?",

    "What is strict mode?",
    "What options does strict mode include?",
    "What is noImplicitAny?",
    "What is strictNullChecks?",
    "What is strictFunctionTypes?",
    "What is strictPropertyInitialization?",
    "What are noUnusedLocals and noUnusedParameters?",
    "What is 'target' in tsconfig?",
    "How to choose target version?",
    "What is 'module' in tsconfig?",
    "What module systems are supported?",
    "What is 'lib' in tsconfig?",
    "How to configure TypeScript libraries?",
    "What are 'paths' in tsconfig?",
    "How to configure path aliases?",

    "How to type DOM elements?",
    "What is the HTMLElement type?",
    "How to type event handlers?",
    "What is the Event type?",
    "How to work with external JavaScript libraries?",
    "What is DefinitelyTyped?",
    "How to install types for a library?",
    "What are @types packages?",
    "How to create types for a JavaScript library?",
    "What is declaration merging?",
    "How to merge type declarations?",
    "What is module augmentation?",
    "How to extend types of an existing module?",
    "What is global augmentation?",
    "How to add global types?",

    "How to test TypeScript code?",
    "What is Jest with TypeScript?",
    "How to set up a testing environment?",
    "How to use mocking in TypeScript?",
    "What are type guards?",
    "How to create a type guard?",
    "What are user-defined type guards?",
    "How to use 'typeof' at runtime?",
    "How to use 'instanceof' in TypeScript?",
    "What are discriminated unions?",
    "How to use discriminated unions?",
    "What is exhaustive checking?",
    "How to ensure exhaustive checks?",
    "What are assert functions?",
    "How to create an assert function?",
  ];

  static const List<String> senior = [
    "What is type-level programming?",
    "How to program at the type level?",
    "What are recursive types?",
    "How to create a recursive type?",
    "What are template literal types?",
    "How to use template literal types?",
    "What are string manipulation types?",
    "How to manipulate strings at the type level?",
    "What is conditional type inference?",
    "How to use 'infer' in complex types?",
    "What are variadic tuple types?",
    "How to use variadic tuples?",
    "What are rest elements in tuple types?",
    "How to use ... in tuple types?",
    "What are labeled tuple elements?",
    "How to use labeled tuples?",
    "What are const type parameters?",
    "How to use 'const' with generic parameters?",
    "What is the 'satisfies' operator?",
    "How to use 'satisfies'?",
    "What is the 'override' keyword?",
    "How to use 'override'?",
    "What are abstract constructors?",
    "How to type abstract constructors?",
    "What are this-based type guards?",

    "How to optimize TypeScript compilation?",
    "What is incremental compilation?",
    "How to set up incremental compilation?",
    "What are project references?",
    "How to use project references?",
    "What are composite projects?",
    "How to set up composite projects?",
    "What is build mode?",
    "How to use the --build flag?",
    "What are declaration maps?",
    "How to set up declaration maps?",
    "What are source maps in TypeScript?",
    "How to set up source maps?",
    "How to reduce compilation time?",
    "What is skipLibCheck?",

    "How to design TypeScript applications?",
    "What is dependency injection in TypeScript?",
    "How to implement DI in TypeScript?",
    "What are decorators?",
    "How to use decorators?",
    "What are class decorators?",
    "What are method decorators?",
    "What are property decorators?",
    "What are parameter decorators?",
    "How to create a custom decorator?",
    "What is metadata reflection?",
    "How to use reflect-metadata?",
    "What are mixins in TypeScript?",
    "How to implement mixins?",
    "What is interface segregation in TypeScript?",
    "How to apply SOLID principles?",
    "What is dependency inversion in TypeScript?",
    "How to design for testability?",
    "What is hexagonal architecture in TypeScript?",
    "How to organize layered architecture?",

    "How to integrate TypeScript with Webpack?",
    "What is ts-loader?",
    "How to configure Webpack for TypeScript?",
    "How to integrate TypeScript with Babel?",
    "What is @babel/preset-typescript?",
    "How to use TypeScript with React?",
    "What is JSX in TypeScript?",
    "How to type React components?",
    "What is the React.FC type?",
    "How to type hooks in React?",
    "How to use TypeScript with Node.js?",
    "How to type Express applications?",
    "What is TypeScript with Vue.js?",
    "How to use TypeScript with Angular?",
    "What is TypeScript in microservice architecture?",

    "How to ensure type safety at runtime?",
    "What is runtime type checking?",
    "How to use Zod for validation?",
    "What is io-ts?",
    "How to use io-ts for validation?",
    "What are type-safe APIs?",
    "How to create a type-safe API?",
    "What is tRPC?",
    "How to use tRPC for type-safe APIs?",
    "What is GraphQL with TypeScript?",
    "How to type GraphQL schemas?",
    "What are type-safe database queries?",
    "How to type database queries?",
    "What is Prisma with TypeScript?",
    "How to ensure end-to-end type safety?",

    "How to analyze TypeScript code?",
    "What is the TypeScript compiler API?",
    "How to use the compiler API?",
    "What is AST in TypeScript?",
    "How to analyze Abstract Syntax Tree?",
    "What is type coverage?",
    "How to measure type coverage?",
    "What is type-level performance?",
    "How to measure type system performance?",
    "What is bundle size analysis for TypeScript?",
  ];
}