// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy1119mtaearwfkWdfbjunhl-d66OTxd0',
    appId: '1:111038140593:web:0380e360ebe3c698231290',
    messagingSenderId: '111038140593',
    projectId: 'fir-cf9f3',
    authDomain: 'fir-cf9f3.firebaseapp.com',
    storageBucket: 'fir-cf9f3.firebasestorage.app',
    measurementId: 'G-YQHGXL2PX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAknBQbsrr52dhk_apoz0NDsPeTgehaQbg',
    appId: '1:111038140593:android:eea98795e60f58b7231290',
    messagingSenderId: '111038140593',
    projectId: 'fir-cf9f3',
    storageBucket: 'fir-cf9f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXtVdvautjHlxH5HJ85RYJQBoROAypeRo',
    appId: '1:111038140593:ios:1cc242af42047a48231290',
    messagingSenderId: '111038140593',
    projectId: 'fir-cf9f3',
    storageBucket: 'fir-cf9f3.firebasestorage.app',
    iosClientId: '111038140593-j43gvj4aeameiqgolen3pbpuiesncb3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.interviewHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXtVdvautjHlxH5HJ85RYJQBoROAypeRo',
    appId: '1:111038140593:ios:1cc242af42047a48231290',
    messagingSenderId: '111038140593',
    projectId: 'fir-cf9f3',
    storageBucket: 'fir-cf9f3.firebasestorage.app',
    iosClientId: '111038140593-j43gvj4aeameiqgolen3pbpuiesncb3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.interviewHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy1119mtaearwfkWdfbjunhl-d66OTxd0',
    appId: '1:111038140593:web:f276701967e5040c231290',
    messagingSenderId: '111038140593',
    projectId: 'fir-cf9f3',
    authDomain: 'fir-cf9f3.firebaseapp.com',
    storageBucket: 'fir-cf9f3.firebasestorage.app',
    measurementId: 'G-KF23W65GGS',
  );
}
