class DevopsQuestions {
  static const List<String> junior = [
    "Что такое DevOps и каковы его основные принципы?",
    "В чем разница между DevOps и традиционными подходами?",
    "Какие основные цели DevOps?",
    "Что такое CI/CD?",
    "Как DevOps связан с Agile методологиями?",
    "Какие основные этапы DevOps жизненного цикла?",
    "Что такое инфраструктура как код (IaC)?",
    "Какие преимущества дает IaC?",
    "Что такое контейнеризация?",
    "В чем разница между виртуальными машинами и контейнерами?",
    "Что такое мониторинг и зачем он нужен?",
    "Какие основные метрики нужно мониторить?",
    "Что такое логирование?",
    "Какие типы логов бывают?",
    "Что такое система контроля версий?",
    "Зачем нужен Git в DevOps?",
    "Что такое артефакты сборки?",
    "Как управлять зависимостями?",
    "Что такое environment (окружение)?",
    "Какие типы окружений бывают?",
    "Что такое deployment?",
    "Какие стратегии деплоя существуют?",
    "Что такое rollback?",
    "Как организовать откат изменений?",
    "Что такое configuration management?",
    "Какие инструменты для управления конфигурацией?",
    "Что такое оркестрация контейнеров?",
    "Зачем нужна оркестрация?",
    "Что такое cloud computing?",
    "Какие модели облачных сервисов существуют?",

    "Что такое Git и как он работает?",
    "Как создать репозиторий в Git?",
    "Как сделать коммит изменений?",
    "Что такое ветки в Git?",
    "Как создать и переключиться на ветку?",
    "Как выполнить слияние веток?",
    "Что такое конфликт слияния?",
    "Как разрешить конфликт в Git?",
    "Что такое pull request?",
    "Как создать pull request?",
    "Что такое code review?",
    "Как проводить код ревью?",
    "Что такое Git hooks?",
    "Как использовать pre-commit hooks?",
    "Что такое .gitignore файл?",
    "Как игнорировать файлы в Git?",
    "Что такое Git flow?",
    "Какие альтернативы Git flow?",
    "Что такое trunk-based development?",
    "Как работает GitHub?",
    "Как работает GitLab?",
    "Что такое Bitbucket?",
    "Как настроить SSH ключи для Git?",
    "Что такое submodules в Git?",
    "Как работать с большими файлами в Git?",

    "Какие основные команды Linux нужно знать?",
    "Как работать с файлами и директориями?",
    "Что такое права доступа в Linux?",
    "Как изменить права доступа?",
    "Как работать с процессами?",
    "Как найти и убить процесс?",
    "Что такое системные демоны?",
    "Как управлять сервисами?",
    "Как работать с системными логами?",
    "Что такое journalctl?",
    "Как настроить сеть в Linux?",
    "Что такое iptables?",
    "Как настроить firewall?",
    "Как работать с пакетными менеджерами?",
    "Что такое apt и yum?",
    "Как установить пакет?",
    "Как обновить систему?",
    "Что такое cron?",
    "Как настроить задание по расписанию?",
    "Как написать bash скрипт?",

    "Что такое Docker?",
    "Как установить Docker?",
    "Что такое Docker image?",
    "Как создать Docker image?",
    "Что такое Docker container?",
    "Как запустить контейнер?",
    "Что такое Dockerfile?",
    "Как написать Dockerfile?",
    "Какие инструкции есть в Dockerfile?",
    "Что такое Docker Hub?",
    "Как выложить image в registry?",
    "Как скачать image из registry?",
    "Что такое Docker volumes?",
    "Как использовать volumes для данных?",
    "Что такое Docker network?",

    "Что такое Jenkins?",
    "Как установить Jenkins?",
    "Как создать pipeline в Jenkins?",
    "Что такое Jenkinsfile?",
    "Как написать declarative pipeline?",
    "Что такое GitHub Actions?",
    "Как создать workflow в GitHub Actions?",
    "Что такое GitLab CI?",
    "Как настроить .gitlab-ci.yml?",
    "Какие этапы typical pipeline?",
  ];

  static const List<String> middle = [
    "Что такое multi-stage builds?",
    "Как уменьшить размер Docker image?",
    "Что такое Docker Compose?",
    "Как использовать docker-compose.yml?",
    "Как оркестрировать несколько контейнеров?",
    "Что такое health checks?",
    "Как настроить проверку здоровья?",
    "Что такое resource limits?",
    "Как ограничить ресурсы контейнера?",
    "Что такое security scanning?",
    "Как сканировать образы на уязвимости?",
    "Что такое Docker registry?",
    "Как настроить private registry?",
    "Что такое image tagging strategies?",
    "Как версионировать образы?",
    "Что такое container runtime?",
    "В чем разница между Docker и containerd?",
    "Что такое Podman?",
    "В чем отличие Podman от Docker?",
    "Что такое Buildah?",

    "Что такое Kubernetes?",
    "Какие основные концепции Kubernetes?",
    "Что такое Pod?",
    "Как создать Pod?",
    "Что такое Deployment?",
    "Как создать Deployment?",
    "Что такое Service?",
    "Какие типы Service существуют?",
    "Что такое ConfigMap?",
    "Как использовать ConfigMap?",
    "Что такое Secret?",
    "Как безопасно хранить секреты?",
    "Что такое Namespace?",
    "Зачем нужны Namespace?",
    "Что такое Ingress?",
    "Как настроить Ingress?",
    "Что такое Helm?",
    "Как создать Helm chart?",
    "Что такое StatefulSet?",
    "Когда использовать StatefulSet?",
    "Что такое DaemonSet?",
    "Когда использовать DaemonSet?",
    "Что такое Job и CronJob?",
    "Как настроить задание по расписанию?",
    "Что такое operator pattern?",

    "Что такое Terraform?",
    "Как установить Terraform?",
    "Что такое HCL?",
    "Как написать конфигурацию Terraform?",
    "Что такое provider в Terraform?",
    "Как использовать AWS provider?",
    "Что такое state в Terraform?",
    "Как управлять state файлом?",
    "Что такое remote state?",
    "Как настроить remote state?",
    "Что такое modules в Terraform?",
    "Как создать модуль?",
    "Что такое Ansible?",
    "Как написать Ansible playbook?",
    "Что такое inventory в Ansible?",
    "Как управлять хостами?",
    "Что такое roles в Ansible?",
    "Как создать роль?",
    "Что такое Packer?",
    "Как создать образ с Packer?",

    "Что такое AWS?",
    "Какие основные сервисы AWS?",
    "Что такое EC2?",
    "Как создать виртуальную машину?",
    "Что такое S3?",
    "Как работать с object storage?",
    "Что такое VPC?",
    "Как настроить сеть в AWS?",
    "Что такое IAM?",
    "Как управлять доступом?",
    "Что такое Azure?",
    "Какие основные сервисы Azure?",
    "Что такое GCP?",
    "Какие основные сервисы GCP?",
    "В чем разница между облачными провайдерами?",

    "Что такое Prometheus?",
    "Как настроить Prometheus?",
    "Что такое metrics?",
    "Какие метрики собирать?",
    "Что такое Grafana?",
    "Как создать dashboard в Grafana?",
    "Что такое Alertmanager?",
    "Как настроить алерты?",
    "Что такое ELK Stack?",
    "Как настроить сбор логов?",
    "Что такое Fluentd?",
    "Как использовать Fluentd для логов?",
    "Что такое Jaeger?",
    "Как настроить distributed tracing?",
    "Что такое APM?",

    "Что такое security в DevOps?",
    "Что такое DevSecOps?",
    "Как интегрировать безопасность в pipeline?",
    "Что такое vulnerability scanning?",
    "Как сканировать образы на уязвимости?",
    "Что такое secret management?",
    "Как использовать HashiCorp Vault?",
    "Что такое network policies?",
    "Как ограничить сетевой трафик?",
    "Что такое pod security policies?",
    "Как ограничить права pod?",
    "Что такое RBAC?",
    "Как настроить ролевой доступ?",
    "Что такое compliance as code?",
    "Как автоматизировать compliance?",
  ];

  static const List<String> senior = [
    "Как проектировать cloud-native архитектуру?",
    "Что такое microservices architecture?",
    "Как разбить монолит на микросервисы?",
    "Что такое service mesh?",
    "Как использовать Istio?",
    "Что такое serverless архитектура?",
    "Когда использовать serverless?",
    "Что такое event-driven architecture?",
    "Как спроектировать event-driven систему?",
    "Что такое CQRS pattern?",
    "Как реализовать CQRS?",
    "Что такое disaster recovery?",
    "Как спроектировать DR стратегию?",
    "Что такое multi-cloud стратегия?",
    "Как работать с несколькими облаками?",
    "Что такое hybrid cloud?",
    "Как интегрировать on-prem и cloud?",
    "Что такое GitOps?",
    "Как реализовать GitOps подход?",
    "Что такое infrastructure as software?",
    "Как использовать программируемую инфраструктуру?",
    "Что такое chaos engineering?",
    "Как проводить chaos experiments?",
    "Что такое SRE?",
    "В чем разница между DevOps и SRE?",

    "Как настроить auto-scaling в Kubernetes?",
    "Что такое HPA и VPA?",
    "Как настроить horizontal pod autoscaling?",
    "Что такое cluster autoscaling?",
    "Как масштабировать кластер?",
    "Что такое service discovery?",
    "Как работает service discovery в Kubernetes?",
    "Что такое etcd?",
    "Как работает etcd в Kubernetes?",
    "Что такое CNI?",
    "Как выбрать network plugin?",
    "Что такое CSI?",
    "Как работать с persistent storage?",
    "Что такое operator framework?",
    "Как создать custom operator?",
    "Что такое service mesh?",
    "Как использовать Linkerd?",
    "Что такое mTLS?",
    "Как настроить mutual TLS?",
    "Что такое admission controllers?",

    "Как построить multi-stage pipeline?",
    "Что такое pipeline as code?",
    "Как реализовать GitOps с ArgoCD?",
    "Что такое FluxCD?",
    "Как настроить continuous deployment?",
    "Что такое blue-green deployment?",
    "Как реализовать blue-green?",
    "Что такое canary deployment?",
    "Как настроить canary releases?",
    "Что такое feature flags?",
    "Как управлять feature flags?",
    "Что такое deployment strategies?",
    "Как выбрать стратегию деплоя?",
    "Что такое progressive delivery?",
    "Как реализовать progressive delivery?",

    "Что такое zero trust architecture?",
    "Как реализовать zero trust?",
    "Что такое security compliance?",
    "Как обеспечить compliance в облаке?",
    "Что такое SOC 2, ISO 27001?",
    "Как подготовиться к аудиту?",
    "Что такое threat modeling?",
    "Как проводить threat modeling?",
    "Что такое penetration testing?",
    "Как организовать pentest?",
    "Что такое security monitoring?",
    "Как настроить SIEM?",
    "Что такое WAF?",
    "Как настроить web application firewall?",
    "Что такое CSPM?",

    "Как оптимизировать costs в облаке?",
    "Что такое FinOps?",
    "Как реализовать FinOps практики?",
    "Как мониторить затраты?",
    "Что такое resource optimization?",
    "Как оптимизировать использование ресурсов?",
    "Что такое performance testing?",
    "Как проводить load testing?",
    "Что такое capacity planning?",
    "Как планировать capacity?",
    "Что такое observability?",
    "Как достичь полной наблюдаемости?",
    "Что такое distributed tracing?",
    "Как анализировать performance issues?",
    "Что такое performance tuning?",

    "Как построить DevOps культуру в организации?",
    "Что такое DevOps maturity model?",
    "Как оценить зрелость DevOps?",
    "Как измерить эффективность DevOps?",
    "Что такое DORA metrics?",
    "Как использовать DORA metrics?",
    "Как управлять техническим долгом?",
    "Как организовать инцидент-менеджмент?",
    "Что такое postmortem анализ?",
    "Как проводить blameless postmortem?",
  ];
}
