class KotlinQuestions {
  static const List<String> junior = [
    "Что такое Kotlin и чем он отличается от Java?",
    "Какие основные типы данных есть в Kotlin?",
    "Как объявить переменную в Kotlin (val vs var)?",
    "Что такое Null Safety в Kotlin?",
    "Как работает оператор безопасного вызова (?.)?",
    "Что такое Elvis оператор (?:) в Kotlin?",
    "Как работает оператор !! в Kotlin?",
    "Какие строковые шаблоны есть в Kotlin?",
    "Как работают условные выражения if и when?",
    "Какие циклы есть в Kotlin (for, while, do-while)?",
    "Как работает range в Kotlin (.., until, downTo)?",
    "Что такое smart cast в Kotlin?",
    "Как объявить и использовать массив в Kotlin?",
    "Как работают коллекции в Kotlin (List, Set, Map)?",
    "В чем разница между List и Array?",
    "Что такое immutable и mutable коллекции?",
    "Как работают функции высшего порядка?",
    "Что такое лямбда-выражения в Kotlin?",
    "Как использовать extension functions?",
    "Что такое infix функции?",
    "Как работают операторы перегрузки?",
    "Что такое data class и чем он отличается от обычного класса?",
    "Как работает деструктуризация (destructuring)?",
    "Что такое sealed class?",
    "Как использовать enum class?",
    "Что такое object declaration?",
    "Как работает companion object?",
    "Что такое inline классы?",
    "Как использовать type aliases?",
    "Что такое reified generics?",

    "Какие модификаторы видимости есть в Kotlin?",
    "Как работает наследование в Kotlin?",
    "Что такое абстрактные классы?",
    "Как работают интерфейсы в Kotlin?",
    "Что такое делегирование (delegation) в Kotlin?",
    "Как использовать делегирование свойств?",
    "Что такое lazy и observable свойства?",
    "Как работают lateinit свойства?",
    "Что такое primary и secondary конструкторы?",
    "Как использовать init блоки?",
    "Что такое inner классы?",
    "Как работают nested классы?",
    "Что такое анонимные классы?",
    "Как использовать generics в Kotlin?",
    "Что такое variance (in, out) в generics?",
    "Как работает where для generics?",
    "Что такое reified type parameters?",
    "Как использовать аннотации в Kotlin?",
    "Что такое reflection в Kotlin?",
    "Как работать с KClass и KFunction?",

    "Что такое pure functions?",
    "Как работают функции высшего порядка?",
    "Что такое лямбда-выражения?",
    "Как использовать анонимные функции?",
    "Что такое function references?",
    "Как работают стандартные функции let, run, with, apply, also?",
    "Что такое sequence в Kotlin?",
    "Как работают операторы map, filter, reduce?",
    "Что такое tailrec функции?",
    "Как использовать coroutines на базовом уровне?",
    "Что такое suspend функции?",
    "Как работает flow в Kotlin?",
    "Что такое channel в Kotlin?",
    "Как использовать select выражение?",
    "Что такое контекст receivers?",

    "Как создать Activity в Kotlin?",
    "Что такое ViewBinding и DataBinding?",
    "Как работать с RecyclerView в Kotlin?",
    "Что такое ViewModel в Android?",
    "Как использовать LiveData?",
    "Что такое Lifecycle-aware компоненты?",
    "Как работать с Room в Kotlin?",
    "Что такое WorkManager?",
    "Как использовать SharedPreferences?",
    "Что такое Intent и как его использовать?",
    "Как работать с Fragments?",
    "Что такое Navigation Component?",
    "Как использовать Retrofit в Kotlin?",
    "Что такое OkHttp?",
    "Как парсить JSON в Kotlin?",
    "Что такое Moshi и Gson?",
    "Как работать с permissions в Android?",
    "Что такое BroadcastReceiver?",
    "Как использовать Services в Android?",
    "Что такое ContentProvider?",

    "Как писать unit тесты в Kotlin?",
    "Что такое JUnit в Kotlin?",
    "Как использовать Mockito в Kotlin?",
    "Что такое Espresso тесты?",
    "Как тестировать ViewModel?",
    "Что такое Instrumentation тесты?",
    "Как дебажить Kotlin код?",
    "Что такое Logcat и как его использовать?",
    "Как работать с breakpoints?",
    "Что такое профилирование в Android Studio?",
    "Как измерять производительность приложения?",
    "Что такое StrictMode?",
    "Как тестировать coroutines?",
    "Что такое MockK?",
    "Как тестировать flow?",
  ];

  static const List<String> middle = [
    "Как работает inline функций в Kotlin?",
    "Что такое reified type parameters?",
    "Как использовать контекстные receivers?",
    "Что такое контравариантность и ковариантность?",
    "Как работает star projection (*)?",
    "Что такое DSL в Kotlin?",
    "Как создать свой DSL?",
    "Что такое аннотации и как их создавать?",
    "Как использовать reflection для анализа классов?",
    "Что такое KAPT и как он работает?",
    "Как использовать Kotlin Poet?",
    "Что такое контракты в Kotlin?",
    "Как работает инлайнинг crossinline и noinline?",
    "Что такое контекстные функции?",
    "Как использовать sealed interfaces?",
    "Что такое value class?",
    "Как работает multi-platform проекты?",
    "Что такое expect/actual механизм?",
    "Как использовать Kotlin/Native?",
    "Что такое Kotlin/JS?",
    "Как работает Kotlin Serialization?",
    "Что такое контекстные параметры?",
    "Как использовать контекстные лямбды?",
    "Что такое контекстные классы?",
    "Как работает контекстное программирование?",

    "Как работает делегирование интерфейсов?",
    "Что такое property delegation?",
    "Как создать свой property delegate?",
    "Что такое lazy и observable свойства?",
    "Как работает lateinit?",
    "Что такое type-safe builders?",
    "Как создать билдер с type-safe?",
    "Что такое композиция vs наследование?",
    "Как использовать паттерн Decorator?",
    "Что такое паттерн Strategy?",
    "Как реализовать паттерн Observer?",
    "Что такое паттерн Factory?",
    "Как использовать паттерн Singleton?",
    "Что такое паттерн Adapter?",
    "Как реализовать паттерн Facade?",
    "Что такое паттерн Proxy?",
    "Как использовать паттерн Command?",
    "Что такое паттерн State?",
    "Как реализовать паттерн Visitor?",
    "Что такое паттерн Builder?",

    "Как работает диспетчер в корутинах?",
    "Что такое Dispatchers.IO, Main, Default?",
    "Как создать свой dispatcher?",
    "Что такое CoroutineScope?",
    "Как работает SupervisorJob?",
    "Что такое CoroutineContext?",
    "Как комбинировать контексты?",
    "Что такое async/await?",
    "Как работает withContext?",
    "Что такое structured concurrency?",
    "Как обрабатывать исключения в корутинах?",
    "Что такое CoroutineExceptionHandler?",
    "Как отменять корутины?",
    "Что такое cancel и join?",
    "Как работает timeout?",
    "Что такое Flow и чем отличается от Channel?",
    "Как использовать StateFlow и SharedFlow?",
    "Что такое cold и hot streams?",
    "Как преобразовывать Flow?",
    "Что такое операторы flow (map, filter, etc)?",

    "Как работает Dagger Hilt?",
    "Что такое dependency injection?",
    "Как создать multi-module приложение?",
    "Что такое dynamic feature modules?",
    "Как работает Navigation Component?",
    "Что такое deep links?",
    "Как использовать ViewModel с SavedState?",
    "Что такое DataStore?",
    "Как работать с Room и Flow?",
    "Что такое Paging Library?",
    "Как использовать WorkManager с корутинами?",
    "Что такое Compose и как его использовать?",
    "Как тестировать Compose UI?",
    "Что такое side effects в Compose?",
    "Как использовать ViewModel в Compose?",
    "Что такое state hoisting?",
    "Как работать с CameraX?",
    "Что такое ML Kit?",
    "Как использовать Biometric API?",
    "Что такое App Bundles?",

    "Как тестировать корутины?",
    "Что такое TestCoroutineDispatcher?",
    "Как mock-ировать suspend функции?",
    "Что такое Turbine для тестирования Flow?",
    "Как тестировать ViewModel с корутинами?",
    "Что такое UI Automator?",
    "Как тестировать Navigation Component?",
    "Что такое hermetic testing?",
    "Как использовать Fake implementations?",
    "Что такое dependency injection для тестирования?",
    "Как измерять покрытие кода?",
    "Что такое mutation testing?",
    "Как использовать static analysis tools?",
    "Что такое Detekt?",
    "Как настроить CI/CD для Android?",
  ];

  static const List<String> senior = [
    "Как проектировать clean architecture?",
    "Что такое domain-driven design?",
    "Как реализовать hexagonal architecture?",
    "Что такое порты и адаптеры?",
    "Как организовать feature modules?",
    "Что такое принцип dependency rule?",
    "Как реализовать onion architecture?",
    "Что такое event sourcing?",
    "Как работать с CQRS?",
    "Как проектировать microservices?",
    "Что такое bounded contexts?",
    "Как реализовать modular monolith?",
    "Что такое vertical slices?",
    "Как организовать shared kernel?",
    "Что такое anti-corruption layer?",
    "Как проектировать для multi-platform?",
    "Что такое MVI архитектура?",
    "Как реализовать Redux?",
    "Что такое Elm architecture?",
    "Как работать с unidirectional data flow?",
    "Что такое state machine?",
    "Как реализовать feature flags?",
    "Что такое A/B testing architecture?",
    "Как проектировать для scalability?",
    "Что такое fault-tolerant systems?",

    "Как профилировать Android приложение?",
    "Что такое Systrace?",
    "Как использовать Android Profiler?",
    "Как оптимизировать запуск приложения?",
    "Что такое cold/warm/hot start?",
    "Как уменьшить размер APK?",
    "Что такое ProGuard и R8?",
    "Как работать с native memory?",
    "Что такое memory leaks?",
    "Как использовать LeakCanary?",
    "Как оптимизировать работу с UI?",
    "Что такое jank и как его исправить?",
    "Как работать с overdraw?",
    "Что такое GPU rendering profiling?",
    "Как оптимизировать работу с сетью?",
    "Что такое HTTP/2 и QUIC?",
    "Как кэшировать данные эффективно?",
    "Что такое stale-while-revalidate?",
    "Как оптимизировать работу с базой данных?",
    "Что такое WAL mode в SQLite?",

    "Как реализовать secure storage?",
    "Что такое Android Keystore?",
    "Как работать с биометрической аутентификацией?",
    "Что такое hardware-backed security?",
    "Как защитить данные в transit?",
    "Что такое certificate pinning?",
    "Как реализовать secure communication?",
    "Что такое TLS 1.3?",
    "Как защитить API?",
    "Что такое OAuth 2.0 и OpenID Connect?",
    "Как реализовать role-based access control?",
    "Что такое attribute-based access control?",
    "Как защитить от reverse engineering?",
    "Что такое obfuscation?",
    "Как использовать native code для безопасности?",
    "Что такое RASP (Runtime Application Self-Protection)?",
    "Как реализовать secure logging?",
    "Что такое GDPR compliance?",
    "Как работать с PII data?",
    "Что такое data minimization principle?",

    "Как организовать code review процесс?",
    "Что такое pair programming?",
    "Как проводить технические собеседования?",
    "Что такое engineering ladder?",
    "Как наставлять junior разработчиков?",
    "Что такое mentorship program?",
    "Как организовать knowledge sharing?",
    "Что такое tech talks?",
    "Как проводить архитектурные обзоры?",
    "Что такое ADR (Architecture Decision Records)?",
    "Как управлять техническим долгом?",
    "Что такое tech debt assessment?",
    "Как организовать CI/CD pipeline?",
    "Что такое trunk-based development?",
    "Как реализовать feature flags management?",
    "Что такое canary releases?",
    "Как организовать incident management?",
    "Что такое postmortem анализ?",
    "Как измерять engineering metrics?",
    "Что такое DORA metrics?",

    "Какие новые фичи в Kotlin?",
    "Что такое Kotlin Multiplatform?",
    "Как работает Kotlin/Wasm?",
    "Что нового в Android development?",
    "Как работает Jetpack Compose под капотом?",
    "Что такое declarative UI?",
    "Как работает Skia в Android?",
    "Что нового в Gradle?",
    "Как работает configuration cache?",
    "Что такое convention plugins?",
    "Как использовать Kotlin в backend?",
    "Что такое Ktor?",
    "Как работает Kotlin/Native memory model?",
    "Что такое new memory manager?",
    "Какие тренды в mobile development?",
  ];
}
