class SwiftQuestions {
  static const List<String> junior = [
  "Что такое Swift и чем он отличается от Objective-C?",
  "Какие основные типы данных есть в Swift?",
  "Как объявить переменную (var) и константу (let)?",
  "Что такое опциональные типы (Optionals) в Swift?",
  "Как работает оператор безопасного извлечения (if let)?",
  "Что такое guard let и чем отличается от if let?",
  "Как работает оператор объединения по nil (??)?",
  "Какие строковые интерполяции есть в Swift?",
  "Как работают условные выражения if и switch?",
  "Какие циклы есть в Swift (for, while, repeat-while)?",
  "Как работают диапазоны (Range) в Swift?",
  "Что такое кортежи (Tuples) в Swift?",
  "Как объявить и использовать массив (Array)?",
  "Как работать со словарем (Dictionary)?",
  "Что такое множество (Set) и когда его использовать?",
  "Как работают замыкания (Closures) в Swift?",
  "Что такое автозамыкания (Autoclosures)?",
  "Как использовать функции высшего порядка (map, filter, reduce)?",
  "Что такое перечисления (enum) в Swift?",
  "Как работают ассоциированные значения в enum?",
  "Что такое raw значения в enum?",
  "Как использовать оператор defer?",
  "Что такое оператор do-try-catch?",
  "Как создавать и бросать ошибки (Error)?",
  "Что такое typealias?",
  "Как работают computed properties?",
  "Что такое property observers (willSet, didSet)?",
  "Как использовать lazy properties?",
  "Что такое subscripts?",
  "Как работать с типами Any и AnyObject?",

  "Как объявить класс (class) и структуру (struct)?",
  "В чем разница между классом и структурой?",
  "Что такое value types и reference types?",
  "Как работает инициализация (init) в Swift?",
  "Что такое designated и convenience инициализаторы?",
  "Как работает наследование в Swift?",
  "Что такое переопределение методов (override)?",
  "Как использовать ключевое слово final?",
  "Что такое протоколы (protocols) в Swift?",
  "Как использовать extension для протоколов?",
  "Что такое protocol composition?",
  "Как работает делегирование (delegation)?",
  "Что такое generics в Swift?",
  "Как использовать where с generics?",
  "Что такое associatedtype в протоколах?",
  "Как работают операторы (operator overloading)?",
  "Что такое custom операторы?",
  "Как использовать access control (open, public, internal, fileprivate, private)?",
  "Что такое memory management в Swift?",
  "Как работает ARC (Automatic Reference Counting)?",
  "Что такое weak и unowned ссылки?",
  "Как избежать retain cycles?",
  "Что такое deinit?",
  "Как использовать KeyPath?",
  "Что такое property wrappers?",

  "Что такое ViewController жизненный цикл?",
  "Как создать UI программно (без storyboard)?",
  "Как работать с UITableView?",
  "Что такое UITableViewDataSource и UITableViewDelegate?",
  "Как использовать UICollectionView?",
  "Как настроить Auto Layout программно?",
  "Что такое Stack Views?",
  "Как работать с UIScrollView?",
  "Что такое responder chain?",
  "Как обрабатывать жесты (UIGestureRecognizer)?",
  "Как работать с анимациями (UIView.animate)?",
  "Что такое Core Animation?",
  "Как использовать UIAlertController?",
  "Что такое UINavigationController?",
  "Как передавать данные между ViewController'ами?",
  "Что такое segue и как его использовать?",
  "Как работать с UITabBarController?",
  "Что такое MVC паттерн в iOS?",
  "Как использовать UserDefaults?",
  "Что такое FileManager?",
  "Как работать с сетью (URLSession)?",
  "Что такое Codable?",
  "Как парсить JSON?",
  "Что такое DispatchQueue?",
  "Как выполнять асинхронные задачи?",

  "Что такое SwiftUI и чем отличается от UIKit?",
  "Как работает View в SwiftUI?",
  "Что такое State и Binding?",
  "Как использовать ObservableObject?",
  "Что такое @Published?",
  "Как работать с List в SwiftUI?",
  "Что такое VStack, HStack, ZStack?",
  "Как использовать модификаторы в SwiftUI?",
  "Что такое @Environment?",
  "Как навигировать в SwiftUI?",

  "Как писать unit тесты в XCTest?",
  "Что такое XCTestCase?",
  "Как использовать XCTAssert?",
  "Что такое test doubles (mock, stub, fake)?",
  "Как тестировать асинхронный код?",
  "Как дебажить Swift код?",
  "Что такое LLDB команды?",
  "Как использовать breakpoints?",
  "Что такое Instruments?",
  "Как измерять производительность приложения?"
  ];

  static const List<String> middle = [
  "Как работает copy-on-write для value types?",
  "Что такое indirect enums?",
  "Как использовать recursive constraints в generics?",
  "Что такое opaque return types (some)?",
  "Как работает @dynamicMemberLookup?",
  "Что такое property wrappers и как создавать свои?",
  "Как использовать @resultBuilder?",
  "Что такое memory layout типов?",
  "Как работать с указателями (UnsafePointer)?",
  "Что такое @autoclosure и когда использовать?",
  "Как реализовать pattern matching?",
  "Что такое ~= оператор?",
  "Как использовать where в протоколах?",
  "Что такое conditional conformance?",
  "Как работает @objc dynamic?",
  "Что такое KeyPath и как использовать?",
  "Как реализовать custom коллекции?",
  "Что такое lazy sequences?",
  "Как использовать Mirror для reflection?",
  "Что такое @available и #available?",
  "Как работать с DispatchGroup?",
  "Что такое Operation и OperationQueue?",
  "Как реализовать custom операторы?",
  "Что такое @inlinable?",
  "Как использовать @main для точки входа?",

  "Как работает multiple inheritance через протоколы?",
  "Что такое protocol oriented programming?",
  "Как использовать protocol extensions?",
  "Что такое default implementations в протоколах?",
  "Как реализовать type erasure?",
  "Что такое existential types?",
  "Как использовать associatedtype в протоколах?",
  "Что такое self и Self в протоколах?",
  "Как реализовать builder pattern?",
  "Что такое dependency injection?",
  "Как использовать factory pattern?",
  "Что такое strategy pattern?",
  "Как реализовать observer pattern?",
  "Что такое decorator pattern?",
  "Как использовать adapter pattern?",
  "Что такое singleton pattern и его плюсы/минусы?",
  "Как реализовать coordinator pattern?",
  "Что такое MVVM паттерн?",
  "Как использовать VIPER архитектуру?",
  "Что такое clean architecture?",

  "Как работает UIViewController жизненный цикл?",
  "Что такое responder chain и как работает?",
  "Как реализовать custom UI компоненты?",
  "Что такое layer-backed views?",
  "Как работать с Core Graphics?",
  "Что такое Core Animation и CALayer?",
  "Как реализовать custom transitions?",
  "Что такое UIResponder и UIEvent?",
  "Как обрабатывать мультитач?",
  "Что такое hit testing?",
  "Как оптимизировать UITableView performance?",
  "Что такое prefetching в UICollectionView?",
  "Как реализовать compositional layout?",
  "Что такое diffable data source?",
  "Как работать с UIScrollView и paging?",
  "Что такое UIScrollViewDelegate методы?",
  "Как реализовать custom UINavigationController?",
  "Что такое UIWindow и UIApplication?",
  "Как работать с UIAppearance?",
  "Что такое trait collections?",

  "Как работает View lifecycle в SwiftUI?",
  "Что такое @StateObject и @ObservedObject?",
  "Как использовать @EnvironmentObject?",
  "Что такое @FetchRequest для Core Data?",
  "Как реализовать custom ViewModifier?",
  "Что такое PreferenceKey?",
  "Как работать с GeometryReader?",
  "Что такое matchedGeometryEffect?",
  "Как реализовать animations в SwiftUI?",
  "Что такое transitions в SwiftUI?",
  "Как использовать @ViewBuilder?",
  "Что такое custom Binding?",
  "Как реализовать Redux в SwiftUI?",
  "Что такое @AppStorage и @SceneStorage?",
  "Как тестировать SwiftUI views?",

  "Как работает DispatchQueue?",
  "Что такое QoS (Quality of Service)?",
  "Как использовать OperationQueue?",
  "Что такое async/await в Swift?",
  "Как работает Task?",
  "Что такое actor в Swift?",
  "Как использовать @MainActor?",
  "Что такое Sendable протокол?",
  "Как избежать data races?",
  "Что такое thread sanitizer?",

  "Как тестировать async код?",
  "Что такое XCTestExpectation?",
  "Как использовать Quick/Nimble?",
  "Что такое snapshot testing?",
  "Как тестировать Combine publishers?",
  "Что такое UI тестирование в XCTest?",
  "Как использовать XCUITest?",
  "Что такое test plans?",
  "Как измерять code coverage?",
  "Что такое performance тесты?"
  ];

  static const List<String> senior = [
  "Как проектировать scalable архитектуру для iOS приложений?",
  "Что такое clean architecture и как применять?",
  "Как реализовать domain-driven design?",
  "Что такое hexagonal architecture?",
  "Как организовать feature modules?",
  "Что такое dependency injection framework?",
  "Как реализовать modular design?",
  "Что такое unidirectional data flow?",
  "Как использовать Redux архитектуру?",
  "Что такое The Composable Architecture (TCA)?",
  "Как реализовать MVVM-C (Coordinator)?",
  "Что такое VIP (View-Interactor-Presenter)?",
  "Как организовать multi-layer архитектуру?",
  "Что такое SOLID принципы?",
  "Как применять принцип dependency inversion?",
  "Что такое interface segregation principle?",
  "Как реализовать event sourcing?",
  "Что такое CQRS pattern?",
  "Как проектировать для testability?",
  "Что такое design system architecture?",
  "Как организовать shared kernel?",
  "Что такое bounded context?",
  "Как реализовать feature flags?",
  "Что такое A/B testing архитектура?",
  "Как проектировать для accessibility?",

  "Как профилировать iOS приложения?",
  "Что такое Instruments и как использовать?",
  "Как измерять memory usage?",
  "Как оптимизировать запуск приложения?",
  "Что такое pre-main и post-main время?",
  "Как уменьшить binary size?",
  "Что такое dead code stripping?",
  "Как использовать dynamic linking?",
  "Что такое app thinning?",
  "Как работать с memory leaks?",
  "Что такое retain cycle detection?",
  "Как использовать memory graph debugger?",
  "Как оптимизировать UITableView performance?",
  "Что такое cell reuse и prefetching?",
  "Как работать с offscreen rendering?",
  "Что такое rasterization?",
  "Как оптимизировать animations?",
  "Что такое CADisplayLink?",
  "Как измерять energy impact?",
  "Что такое power consumption optimization?",

  "Как реализовать secure storage?",
  "Что такое Keychain Services?",
  "Как работать с биометрической аутентификацией?",
  "Что такое LocalAuthentication framework?",
  "Как защитить данные в transit?",
  "Что такое certificate pinning?",
  "Как реализовать secure network layer?",
  "Что такое App Transport Security?",
  "Как защитить от MITM атак?",
  "Что такое OAuth 2.0 и OpenID Connect?",
  "Как реализовать JWT authentication?",
  "Что такое role-based access control?",
  "Как защитить от reverse engineering?",
  "Что такое obfuscation techniques?",
  "Как использовать C код для безопасности?",
  "Что такое RASP (Runtime App Self-Protection)?",
  "Как реализовать secure logging?",
  "Что такое GDPR compliance?",
  "Как работать с PII data?",
  "Что такое data minimization principle?",

  "Как организовать code review процесс?",
  "Что такое pair programming?",
  "Как проводить технические собеседования?",
  "Что такое engineering ladder?",
  "Как наставлять junior разработчиков?",
  "Что такое mentorship program?",
  "Как организовать knowledge sharing?",
  "Что такое tech talks?",
  "Как проводить архитектурные обзоры?",
  "Что такое ADR (Architecture Decision Records)?",
  "Как управлять техническим долгом?",
  "Что такое tech debt assessment?",
  "Как организовать CI/CD pipeline?",
  "Что такое trunk-based development?",
  "Как реализовать feature flags management?",

  "Какие новые фичи в Swift?",
  "Что такое Swift Concurrency?",
  "Как работает actor model?",
  "Что такое distributed actors?",
  "Как использовать Swift for server-side?",
  "Что такое Vapor framework?",
  "Как работает SwiftNIO?",
  "Что нового в SwiftUI?",
  "Как использовать Swift Charts?",
  "Что такое Swift Regex?",
  "Как работает Swift macros?",
  "Что такое embedded DSL?",
  "Как использовать machine learning в iOS?",
  "Что такое Core ML?",
  "Как работать с Create ML?",
  "Что такое ARKit и RealityKit?",
  "Как реализовать AR experiences?",
  "Что такое Swift Playgrounds?",
  "Как использовать Swift on Linux?",
  "Какие тренды в iOS development?"
  ];
}